/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-stuff/ASN1-C-ITS/CPMv1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_AnimalSubclassV1_H_
#define	_AnimalSubclassV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "AnimalSubclassTypeV1.h"
#include "ClassConfidenceV1.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AnimalSubclassV1 */
typedef struct AnimalSubclassV1 {
	AnimalSubclassTypeV1_t	 type;	/* DEFAULT 0 */
	ClassConfidenceV1_t	 confidence;	/* DEFAULT 0 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AnimalSubclassV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AnimalSubclassV1;
extern asn_SEQUENCE_specifics_t asn_SPC_AnimalSubclassV1_specs_1;
extern asn_TYPE_member_t asn_MBR_AnimalSubclassV1_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _AnimalSubclassV1_H_ */
#include "asn_internal.h"
