/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/mnt/EVO/ASN1-C-ITS/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_CauseCodeTypeV1_H_
#define	_CauseCodeTypeV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CauseCodeTypeV1 {
	CauseCodeTypeV1_reserved	= 0,
	CauseCodeTypeV1_trafficCondition	= 1,
	CauseCodeTypeV1_accident	= 2,
	CauseCodeTypeV1_roadworks	= 3,
	CauseCodeTypeV1_adverseWeatherCondition_Adhesion	= 6,
	CauseCodeTypeV1_hazardousLocation_SurfaceCondition	= 9,
	CauseCodeTypeV1_hazardousLocation_ObstacleOnTheRoad	= 10,
	CauseCodeTypeV1_hazardousLocation_AnimalOnTheRoad	= 11,
	CauseCodeTypeV1_humanPresenceOnTheRoad	= 12,
	CauseCodeTypeV1_wrongWayDriving	= 14,
	CauseCodeTypeV1_rescueAndRecoveryWorkInProgress	= 15,
	CauseCodeTypeV1_adverseWeatherCondition_ExtremeWeatherCondition	= 17,
	CauseCodeTypeV1_adverseWeatherCondition_Visibility	= 18,
	CauseCodeTypeV1_adverseWeatherCondition_Precipitation	= 19,
	CauseCodeTypeV1_slowVehicle	= 26,
	CauseCodeTypeV1_dangerousEndOfQueue	= 27,
	CauseCodeTypeV1_vehicleBreakdown	= 91,
	CauseCodeTypeV1_postCrash	= 92,
	CauseCodeTypeV1_humanProblem	= 93,
	CauseCodeTypeV1_stationaryVehicle	= 94,
	CauseCodeTypeV1_emergencyVehicleApproaching	= 95,
	CauseCodeTypeV1_hazardousLocation_DangerousCurve	= 96,
	CauseCodeTypeV1_collisionRisk	= 97,
	CauseCodeTypeV1_signalViolation	= 98,
	CauseCodeTypeV1_dangerousSituation	= 99
} e_CauseCodeTypeV1;

/* CauseCodeTypeV1 */
typedef long	 CauseCodeTypeV1_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_CauseCodeTypeV1_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_CauseCodeTypeV1;
asn_struct_free_f CauseCodeTypeV1_free;
asn_struct_print_f CauseCodeTypeV1_print;
asn_constr_check_f CauseCodeTypeV1_constraint;
ber_type_decoder_f CauseCodeTypeV1_decode_ber;
der_type_encoder_f CauseCodeTypeV1_encode_der;
xer_type_decoder_f CauseCodeTypeV1_decode_xer;
xer_type_encoder_f CauseCodeTypeV1_encode_xer;
oer_type_decoder_f CauseCodeTypeV1_decode_oer;
oer_type_encoder_f CauseCodeTypeV1_encode_oer;
per_type_decoder_f CauseCodeTypeV1_decode_uper;
per_type_encoder_f CauseCodeTypeV1_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CauseCodeTypeV1_H_ */
#include "asn_internal.h"
