/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-stuff/ASN1-C-ITS/CPMv1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_ClassConfidenceV1_H_
#define	_ClassConfidenceV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ClassConfidenceV1 {
	ClassConfidenceV1_unknown	= 0,
	ClassConfidenceV1_onePercent	= 1,
	ClassConfidenceV1_oneHundredPercent	= 100,
	ClassConfidenceV1_unavailable	= 101
} e_ClassConfidenceV1;

/* ClassConfidenceV1 */
typedef long	 ClassConfidenceV1_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ClassConfidenceV1_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ClassConfidenceV1;
asn_struct_free_f ClassConfidenceV1_free;
asn_struct_print_f ClassConfidenceV1_print;
asn_constr_check_f ClassConfidenceV1_constraint;
ber_type_decoder_f ClassConfidenceV1_decode_ber;
der_type_encoder_f ClassConfidenceV1_encode_der;
xer_type_decoder_f ClassConfidenceV1_decode_xer;
xer_type_encoder_f ClassConfidenceV1_encode_xer;
oer_type_decoder_f ClassConfidenceV1_decode_oer;
oer_type_encoder_f ClassConfidenceV1_encode_oer;
per_type_decoder_f ClassConfidenceV1_decode_uper;
per_type_encoder_f ClassConfidenceV1_encode_uper;
per_type_decoder_f ClassConfidenceV1_decode_aper;
per_type_encoder_f ClassConfidenceV1_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ClassConfidenceV1_H_ */
#include "asn_internal.h"
