/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/mnt/EVO/ASN1-C-ITS/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_CurvatureV1_H_
#define	_CurvatureV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "CurvatureValueV1.h"
#include "CurvatureConfidenceV1.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CurvatureV1 */
typedef struct CurvatureV1 {
	CurvatureValueV1_t	 curvatureValue;
	CurvatureConfidenceV1_t	 curvatureConfidence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CurvatureV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CurvatureV1;
extern asn_SEQUENCE_specifics_t asn_SPC_CurvatureV1_specs_1;
extern asn_TYPE_member_t asn_MBR_CurvatureV1_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _CurvatureV1_H_ */
#include "asn_internal.h"
