/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "GDD"
 * 	found in "/mnt/EVO/ASN1-C-ITS/GDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_DestinationPlace_H_
#define	_DestinationPlace_H_


#include "asn_application.h"

/* Including external dependencies */
#include "DDD-DEP.h"
#include "OCTET_STRING.h"
#include "NativeInteger.h"
#include "UTF8String.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ISO14823Code;

/* DestinationPlace */
typedef struct DestinationPlace {
	DDD_DEP_t	 depType;
	struct ISO14823Code	*depRSCode	/* OPTIONAL */;
	OCTET_STRING_t	*depBlob	/* OPTIONAL */;
	long	*plnId	/* OPTIONAL */;
	UTF8String_t	*plnText	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DestinationPlace_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DestinationPlace;
extern asn_SEQUENCE_specifics_t asn_SPC_DestinationPlace_specs_1;
extern asn_TYPE_member_t asn_MBR_DestinationPlace_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ISO14823Code.h"

#endif	/* _DestinationPlace_H_ */
#include "asn_internal.h"
