/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_EnergyStorageType_H_
#define	_EnergyStorageType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EnergyStorageType {
	EnergyStorageType_hydrogenStorage	= 0,
	EnergyStorageType_electricEnergyStorage	= 1,
	EnergyStorageType_liquidPropaneGas	= 2,
	EnergyStorageType_compressedNaturalGas	= 3,
	EnergyStorageType_diesel	= 4,
	EnergyStorageType_gasoline	= 5,
	EnergyStorageType_ammonia	= 6
} e_EnergyStorageType;

/* EnergyStorageType */
typedef BIT_STRING_t	 EnergyStorageType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EnergyStorageType;
asn_struct_free_f EnergyStorageType_free;
asn_struct_print_f EnergyStorageType_print;
asn_constr_check_f EnergyStorageType_constraint;
ber_type_decoder_f EnergyStorageType_decode_ber;
der_type_encoder_f EnergyStorageType_encode_der;
xer_type_decoder_f EnergyStorageType_decode_xer;
xer_type_encoder_f EnergyStorageType_encode_xer;
jer_type_encoder_f EnergyStorageType_encode_jer;
oer_type_decoder_f EnergyStorageType_decode_oer;
oer_type_encoder_f EnergyStorageType_encode_oer;
per_type_decoder_f EnergyStorageType_decode_uper;
per_type_encoder_f EnergyStorageType_encode_uper;
per_type_decoder_f EnergyStorageType_decode_aper;
per_type_encoder_f EnergyStorageType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _EnergyStorageType_H_ */
#include "asn_internal.h"
