/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "/mnt/EVO/asn1c-forks/output/CPM-all.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_MessageRateRange_H_
#define	_MessageRateRange_H_


#include "asn_application.h"

/* Including external dependencies */
#include "MessageRateHz.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* MessageRateRange */
typedef struct MessageRateRange {
	MessageRateHz_t	 messageRateMin;
	MessageRateHz_t	 messageRateMax;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MessageRateRange_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MessageRateRange;
extern asn_SEQUENCE_specifics_t asn_SPC_MessageRateRange_specs_1;
extern asn_TYPE_member_t asn_MBR_MessageRateRange_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _MessageRateRange_H_ */
#include "asn_internal.h"
