/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_RelevanceTrafficDirection_H_
#define	_RelevanceTrafficDirection_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RelevanceTrafficDirection {
	RelevanceTrafficDirection_allTrafficDirections	= 0,
	RelevanceTrafficDirection_upstreamTraffic	= 1,
	RelevanceTrafficDirection_downstreamTraffic	= 2,
	RelevanceTrafficDirection_oppositeTraffic	= 3
} e_RelevanceTrafficDirection;

/* RelevanceTrafficDirection */
typedef long	 RelevanceTrafficDirection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RelevanceTrafficDirection;
asn_struct_free_f RelevanceTrafficDirection_free;
asn_struct_print_f RelevanceTrafficDirection_print;
asn_constr_check_f RelevanceTrafficDirection_constraint;
ber_type_decoder_f RelevanceTrafficDirection_decode_ber;
der_type_encoder_f RelevanceTrafficDirection_encode_der;
xer_type_decoder_f RelevanceTrafficDirection_decode_xer;
xer_type_encoder_f RelevanceTrafficDirection_encode_xer;
jer_type_encoder_f RelevanceTrafficDirection_encode_jer;
oer_type_decoder_f RelevanceTrafficDirection_decode_oer;
oer_type_encoder_f RelevanceTrafficDirection_encode_oer;
per_type_decoder_f RelevanceTrafficDirection_decode_uper;
per_type_encoder_f RelevanceTrafficDirection_encode_uper;
per_type_decoder_f RelevanceTrafficDirection_decode_aper;
per_type_encoder_f RelevanceTrafficDirection_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RelevanceTrafficDirection_H_ */
#include "asn_internal.h"
