/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/mnt/EVO/ASN1-C-ITS/DSRC.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_RestrictionClassAssignment_H_
#define	_RestrictionClassAssignment_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RestrictionClassID.h"
#include "RestrictionUserTypeList.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RestrictionClassAssignment */
typedef struct RestrictionClassAssignment {
	RestrictionClassID_t	 id;
	RestrictionUserTypeList_t	 users;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RestrictionClassAssignment_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RestrictionClassAssignment;
extern asn_SEQUENCE_specifics_t asn_SPC_RestrictionClassAssignment_specs_1;
extern asn_TYPE_member_t asn_MBR_RestrictionClassAssignment_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RestrictionClassAssignment_H_ */
#include "asn_internal.h"
