/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "/mnt/EVO/ASN1-C-ITS/ISO14906(2018)EfcDsrcApplicationv6-patched.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_ResultFin_H_
#define	_ResultFin_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ResultFin */
typedef OCTET_STRING_t	 ResultFin_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ResultFin_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ResultFin;
asn_struct_free_f ResultFin_free;
asn_struct_print_f ResultFin_print;
asn_constr_check_f ResultFin_constraint;
ber_type_decoder_f ResultFin_decode_ber;
der_type_encoder_f ResultFin_encode_der;
xer_type_decoder_f ResultFin_decode_xer;
xer_type_encoder_f ResultFin_encode_xer;
oer_type_decoder_f ResultFin_decode_oer;
oer_type_encoder_f ResultFin_encode_oer;
per_type_decoder_f ResultFin_decode_uper;
per_type_encoder_f ResultFin_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ResultFin_H_ */
#include "asn_internal.h"
