/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-SensorInformationContainer"
 * 	found in "/mnt/EVO/asn1c-forks/output/CPM-all.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_SensorInformationContainer_H_
#define	_SensorInformationContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SensorInformation;

/* SensorInformationContainer */
typedef struct SensorInformationContainer {
	A_SEQUENCE_OF(struct SensorInformation) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SensorInformationContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SensorInformationContainer;
extern asn_SET_OF_specifics_t asn_SPC_SensorInformationContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_SensorInformationContainer_1[1];
extern asn_per_constraints_t asn_PER_type_SensorInformationContainer_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SensorInformation.h"

#endif	/* _SensorInformationContainer_H_ */
#include "asn_internal.h"
