/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-stuff/ASN1-C-ITS/CPMv1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_StationDataContainerV1_H_
#define	_StationDataContainerV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OriginatingVehicleContainerV1.h"
#include "OriginatingRSUContainerV1.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum StationDataContainerV1_PR {
	StationDataContainerV1_PR_NOTHING,	/* No components present */
	StationDataContainerV1_PR_originatingVehicleContainer,
	StationDataContainerV1_PR_originatingRSUContainer
	/* Extensions may appear below */
	
} StationDataContainerV1_PR;

/* StationDataContainerV1 */
typedef struct StationDataContainerV1 {
	StationDataContainerV1_PR present;
	union StationDataContainerV1_u {
		OriginatingVehicleContainerV1_t	 originatingVehicleContainer;
		OriginatingRSUContainerV1_t	 originatingRSUContainer;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} StationDataContainerV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StationDataContainerV1;
extern asn_CHOICE_specifics_t asn_SPC_StationDataContainerV1_specs_1;
extern asn_TYPE_member_t asn_MBR_StationDataContainerV1_1[2];
extern asn_per_constraints_t asn_PER_type_StationDataContainerV1_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _StationDataContainerV1_H_ */
#include "asn_internal.h"
