/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "/mnt/EVO/ASN1-C-ITS/ISO14906(2018)EfcDsrcApplicationv6-patched.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_TrailerLicencePlateNumber_H_
#define	_TrailerLicencePlateNumber_H_


#include "asn_application.h"

/* Including external dependencies */
#include "LPN.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TrailerLicencePlateNumber */
typedef LPN_t	 TrailerLicencePlateNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TrailerLicencePlateNumber;
asn_struct_free_f TrailerLicencePlateNumber_free;
asn_struct_print_f TrailerLicencePlateNumber_print;
asn_constr_check_f TrailerLicencePlateNumber_constraint;
ber_type_decoder_f TrailerLicencePlateNumber_decode_ber;
der_type_encoder_f TrailerLicencePlateNumber_encode_der;
xer_type_decoder_f TrailerLicencePlateNumber_decode_xer;
xer_type_encoder_f TrailerLicencePlateNumber_encode_xer;
oer_type_decoder_f TrailerLicencePlateNumber_decode_oer;
oer_type_encoder_f TrailerLicencePlateNumber_encode_oer;
per_type_decoder_f TrailerLicencePlateNumber_decode_uper;
per_type_encoder_f TrailerLicencePlateNumber_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TrailerLicencePlateNumber_H_ */
#include "asn_internal.h"
