/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_TurningDirection_H_
#define	_TurningDirection_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TurningDirection {
	TurningDirection_left	= 0,
	TurningDirection_right	= 1
} e_TurningDirection;

/* TurningDirection */
typedef long	 TurningDirection_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TurningDirection_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TurningDirection;
extern const asn_INTEGER_specifics_t asn_SPC_TurningDirection_specs_1;
asn_struct_free_f TurningDirection_free;
asn_struct_print_f TurningDirection_print;
asn_constr_check_f TurningDirection_constraint;
ber_type_decoder_f TurningDirection_decode_ber;
der_type_encoder_f TurningDirection_encode_der;
xer_type_decoder_f TurningDirection_decode_xer;
xer_type_encoder_f TurningDirection_encode_xer;
jer_type_encoder_f TurningDirection_encode_jer;
oer_type_decoder_f TurningDirection_decode_oer;
oer_type_encoder_f TurningDirection_encode_oer;
per_type_decoder_f TurningDirection_decode_uper;
per_type_encoder_f TurningDirection_encode_uper;
per_type_decoder_f TurningDirection_decode_aper;
per_type_encoder_f TurningDirection_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _TurningDirection_H_ */
#include "asn_internal.h"
