/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-C-ITS/VAM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_VamParameters_H_
#define	_VamParameters_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BasicContainer.h"
#include "VruHighFrequencyContainer.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VruLowFrequencyContainer;
struct VruClusterInformationContainer;
struct VruClusterOperationContainer;
struct VruMotionPredictionContainer;

/* VamParameters */
typedef struct VamParameters {
	BasicContainer_t	 basicContainer;
	VruHighFrequencyContainer_t	 vruHighFrequencyContainer;
	struct VruLowFrequencyContainer	*vruLowFrequencyContainer	/* OPTIONAL */;
	struct VruClusterInformationContainer	*vruClusterInformationContainer	/* OPTIONAL */;
	struct VruClusterOperationContainer	*vruClusterOperationContainer	/* OPTIONAL */;
	struct VruMotionPredictionContainer	*vruMotionPredictionContainer	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VamParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VamParameters;
extern asn_SEQUENCE_specifics_t asn_SPC_VamParameters_specs_1;
extern asn_TYPE_member_t asn_MBR_VamParameters_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VruLowFrequencyContainer.h"
#include "VruClusterInformationContainer.h"
#include "VruClusterOperationContainer.h"
#include "VruMotionPredictionContainer.h"

#endif	/* _VamParameters_H_ */
#include "asn_internal.h"
