/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "/mnt/EVO/ASN1-C-ITS/ISO14906(2018)EfcDsrcApplicationv6-patched.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_VehicleSpecificCharacteristics_H_
#define	_VehicleSpecificCharacteristics_H_


#include "asn_application.h"

/* Including external dependencies */
#include "EnvironmentalCharacteristics.h"
#include "EngineCharacteristics.h"
#include "DescriptiveCharacteristics.h"
#include "FutureCharacteristics.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleSpecificCharacteristics */
typedef struct VehicleSpecificCharacteristics {
	EnvironmentalCharacteristics_t	 environmentalCharacteristics;
	EngineCharacteristics_t	 engineCharacteristics;
	DescriptiveCharacteristics_t	 descriptiveCharacteristics;
	FutureCharacteristics_t	 futureCharacteristics;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleSpecificCharacteristics_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleSpecificCharacteristics;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleSpecificCharacteristics_H_ */
#include "asn_internal.h"
