/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-stuff/ASN1-C-ITS/CPMv1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_VehicleSubclassTypeV1_H_
#define	_VehicleSubclassTypeV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VehicleSubclassTypeV1 {
	VehicleSubclassTypeV1_unknown	= 0,
	VehicleSubclassTypeV1_moped	= 1,
	VehicleSubclassTypeV1_motorcycle	= 2,
	VehicleSubclassTypeV1_passengerCar	= 3,
	VehicleSubclassTypeV1_bus	= 4,
	VehicleSubclassTypeV1_lightTruck	= 5,
	VehicleSubclassTypeV1_heavyTruck	= 6,
	VehicleSubclassTypeV1_trailer	= 7,
	VehicleSubclassTypeV1_specialVehicles	= 8,
	VehicleSubclassTypeV1_tram	= 9,
	VehicleSubclassTypeV1_emergencyVehicle	= 10,
	VehicleSubclassTypeV1_agricultural	= 11
} e_VehicleSubclassTypeV1;

/* VehicleSubclassTypeV1 */
typedef long	 VehicleSubclassTypeV1_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_VehicleSubclassTypeV1_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_VehicleSubclassTypeV1;
asn_struct_free_f VehicleSubclassTypeV1_free;
asn_struct_print_f VehicleSubclassTypeV1_print;
asn_constr_check_f VehicleSubclassTypeV1_constraint;
ber_type_decoder_f VehicleSubclassTypeV1_decode_ber;
der_type_encoder_f VehicleSubclassTypeV1_encode_der;
xer_type_decoder_f VehicleSubclassTypeV1_decode_xer;
xer_type_encoder_f VehicleSubclassTypeV1_encode_xer;
oer_type_decoder_f VehicleSubclassTypeV1_decode_oer;
oer_type_encoder_f VehicleSubclassTypeV1_encode_oer;
per_type_decoder_f VehicleSubclassTypeV1_decode_uper;
per_type_encoder_f VehicleSubclassTypeV1_encode_uper;
per_type_decoder_f VehicleSubclassTypeV1_decode_aper;
per_type_encoder_f VehicleSubclassTypeV1_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleSubclassTypeV1_H_ */
#include "asn_internal.h"
