/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_VruDeviceUsage_H_
#define	_VruDeviceUsage_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VruDeviceUsage {
	VruDeviceUsage_unavailable	= 0,
	VruDeviceUsage_other	= 1,
	VruDeviceUsage_idle	= 2,
	VruDeviceUsage_listeningToAudio	= 3,
	VruDeviceUsage_typing	= 4,
	VruDeviceUsage_calling	= 5,
	VruDeviceUsage_playingGames	= 6,
	VruDeviceUsage_reading	= 7,
	VruDeviceUsage_viewing	= 8,
	VruDeviceUsage_max	= 255
} e_VruDeviceUsage;

/* VruDeviceUsage */
typedef long	 VruDeviceUsage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VruDeviceUsage;
asn_struct_free_f VruDeviceUsage_free;
asn_struct_print_f VruDeviceUsage_print;
asn_constr_check_f VruDeviceUsage_constraint;
ber_type_decoder_f VruDeviceUsage_decode_ber;
der_type_encoder_f VruDeviceUsage_encode_der;
xer_type_decoder_f VruDeviceUsage_decode_xer;
xer_type_encoder_f VruDeviceUsage_encode_xer;
jer_type_encoder_f VruDeviceUsage_encode_jer;
oer_type_decoder_f VruDeviceUsage_decode_oer;
oer_type_encoder_f VruDeviceUsage_encode_oer;
per_type_decoder_f VruDeviceUsage_decode_uper;
per_type_encoder_f VruDeviceUsage_encode_uper;
per_type_decoder_f VruDeviceUsage_decode_aper;
per_type_encoder_f VruDeviceUsage_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _VruDeviceUsage_H_ */
#include "asn_internal.h"
