/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_VruEnvironment_H_
#define	_VruEnvironment_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VruEnvironment {
	VruEnvironment_unavailable	= 0,
	VruEnvironment_intersectionCrossing	= 1,
	VruEnvironment_zebraCrossing	= 2,
	VruEnvironment_sidewalk	= 3,
	VruEnvironment_onVehicleRoad	= 4,
	VruEnvironment_protectedGeographicArea	= 5,
	VruEnvironment_max	= 255
} e_VruEnvironment;

/* VruEnvironment */
typedef long	 VruEnvironment_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VruEnvironment;
asn_struct_free_f VruEnvironment_free;
asn_struct_print_f VruEnvironment_print;
asn_constr_check_f VruEnvironment_constraint;
ber_type_decoder_f VruEnvironment_decode_ber;
der_type_encoder_f VruEnvironment_encode_der;
xer_type_decoder_f VruEnvironment_decode_xer;
xer_type_encoder_f VruEnvironment_encode_xer;
jer_type_encoder_f VruEnvironment_encode_jer;
oer_type_decoder_f VruEnvironment_decode_oer;
oer_type_encoder_f VruEnvironment_encode_oer;
per_type_decoder_f VruEnvironment_decode_uper;
per_type_encoder_f VruEnvironment_encode_uper;
per_type_decoder_f VruEnvironment_decode_aper;
per_type_encoder_f VruEnvironment_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _VruEnvironment_H_ */
#include "asn_internal.h"
