/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-C-ITS/VAM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_VruHighFrequencyContainer_H_
#define	_VruHighFrequencyContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Wgs84Angle.h"
#include "Speed.h"
#include "LongitudinalAcceleration.h"
#include "CurvatureCalculationMode.h"
#include "VruEnvironment.h"
#include "VruMovementControl.h"
#include "VruDeviceUsage.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Curvature;
struct YawRate;
struct LateralAcceleration;
struct VerticalAcceleration;
struct GeneralizedLanePosition;
struct Wgs84Angle;
struct CartesianAngle;

/* VruHighFrequencyContainer */
typedef struct VruHighFrequencyContainer {
	Wgs84Angle_t	 heading;
	Speed_t	 speed;
	LongitudinalAcceleration_t	 longitudinalAcceleration;
	struct Curvature	*curvature	/* OPTIONAL */;
	CurvatureCalculationMode_t	*curvatureCalculationMode	/* OPTIONAL */;
	struct YawRate	*yawRate	/* OPTIONAL */;
	struct LateralAcceleration	*lateralAcceleration	/* OPTIONAL */;
	struct VerticalAcceleration	*verticalAcceleration	/* OPTIONAL */;
	struct GeneralizedLanePosition	*vruLanePosition	/* OPTIONAL */;
	VruEnvironment_t	*environment	/* OPTIONAL */;
	VruMovementControl_t	*movementControl	/* OPTIONAL */;
	struct Wgs84Angle	*orientation	/* OPTIONAL */;
	struct CartesianAngle	*rollAngle	/* OPTIONAL */;
	VruDeviceUsage_t	*deviceUsage	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VruHighFrequencyContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VruHighFrequencyContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_VruHighFrequencyContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_VruHighFrequencyContainer_1[14];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Curvature.h"
#include "YawRate.h"
#include "LateralAcceleration.h"
#include "VerticalAcceleration.h"
#include "GeneralizedLanePosition.h"
#include "Wgs84Angle.h"
#include "CartesianAngle.h"

#endif	/* _VruHighFrequencyContainer_H_ */
#include "asn_internal.h"
