/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "ETSI-ITS-CDD.asn"
 */

#ifndef	_Acceleration3dWithConfidence_H_
#define	_Acceleration3dWithConfidence_H_


#include "asn_application.h"

/* Including external dependencies */
#include "AccelerationPolarWithZ.h"
#include "AccelerationCartesian.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Acceleration3dWithConfidence_PR {
	Acceleration3dWithConfidence_PR_NOTHING,	/* No components present */
	Acceleration3dWithConfidence_PR_polarAcceleration,
	Acceleration3dWithConfidence_PR_cartesianAcceleration
} Acceleration3dWithConfidence_PR;

/* Acceleration3dWithConfidence */
typedef struct Acceleration3dWithConfidence {
	Acceleration3dWithConfidence_PR present;
	union Acceleration3dWithConfidence_u {
		AccelerationPolarWithZ_t	 polarAcceleration;
		AccelerationCartesian_t	 cartesianAcceleration;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Acceleration3dWithConfidence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Acceleration3dWithConfidence;
extern asn_CHOICE_specifics_t asn_SPC_Acceleration3dWithConfidence_specs_1;
extern asn_TYPE_member_t asn_MBR_Acceleration3dWithConfidence_1[2];
extern asn_per_constraints_t asn_PER_type_Acceleration3dWithConfidence_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Acceleration3dWithConfidence_H_ */
#include "asn_internal.h"
