/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "ETSI-ITS-CDD.asn"
 */

#ifndef	_AngularSpeedConfidence_H_
#define	_AngularSpeedConfidence_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AngularSpeedConfidence {
	AngularSpeedConfidence_degSec_01	= 0,
	AngularSpeedConfidence_degSec_02	= 1,
	AngularSpeedConfidence_degSec_05	= 2,
	AngularSpeedConfidence_degSec_10	= 3,
	AngularSpeedConfidence_degSec_20	= 4,
	AngularSpeedConfidence_degSec_50	= 5,
	AngularSpeedConfidence_outOfRange	= 6,
	AngularSpeedConfidence_unavailable	= 7
} e_AngularSpeedConfidence;

/* AngularSpeedConfidence */
typedef long	 AngularSpeedConfidence_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AngularSpeedConfidence_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AngularSpeedConfidence;
extern const asn_INTEGER_specifics_t asn_SPC_AngularSpeedConfidence_specs_1;
asn_struct_free_f AngularSpeedConfidence_free;
asn_struct_print_f AngularSpeedConfidence_print;
asn_constr_check_f AngularSpeedConfidence_constraint;
ber_type_decoder_f AngularSpeedConfidence_decode_ber;
der_type_encoder_f AngularSpeedConfidence_encode_der;
xer_type_decoder_f AngularSpeedConfidence_decode_xer;
xer_type_encoder_f AngularSpeedConfidence_encode_xer;
oer_type_decoder_f AngularSpeedConfidence_decode_oer;
oer_type_encoder_f AngularSpeedConfidence_encode_oer;
per_type_decoder_f AngularSpeedConfidence_decode_uper;
per_type_encoder_f AngularSpeedConfidence_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AngularSpeedConfidence_H_ */
#include "asn_internal.h"
