/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "ITS-Container.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_CenDsrcTollingZoneV1_H_
#define	_CenDsrcTollingZoneV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "LatitudeV1.h"
#include "LongitudeV1.h"
#include "CenDsrcTollingZoneIDV1.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CenDsrcTollingZoneV1 */
typedef struct CenDsrcTollingZoneV1 {
	LatitudeV1_t	 protectedZoneLatitude;
	LongitudeV1_t	 protectedZoneLongitude;
	CenDsrcTollingZoneIDV1_t	*cenDsrcTollingZoneID	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CenDsrcTollingZoneV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CenDsrcTollingZoneV1;
extern asn_SEQUENCE_specifics_t asn_SPC_CenDsrcTollingZoneV1_specs_1;
extern asn_TYPE_member_t asn_MBR_CenDsrcTollingZoneV1_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _CenDsrcTollingZoneV1_H_ */
#include "asn_internal.h"
