/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "asn1/TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_CpmParameters_H_
#define	_CpmParameters_H_


#include "asn_application.h"

/* Including external dependencies */
#include "CpmManagementContainer.h"
#include "NumberOfPerceivedObjects.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct StationDataContainer;
struct SensorInformationContainer;
struct PerceivedObjectContainer;
struct FreeSpaceAddendumContainer;

/* CpmParameters */
typedef struct CpmParameters {
	CpmManagementContainer_t	 managementContainer;
	struct StationDataContainer	*stationDataContainer;	/* OPTIONAL */
	struct SensorInformationContainer	*sensorInformationContainer;	/* OPTIONAL */
	struct PerceivedObjectContainer	*perceivedObjectContainer;	/* OPTIONAL */
	struct FreeSpaceAddendumContainer	*freeSpaceAddendumContainer;	/* OPTIONAL */
	NumberOfPerceivedObjects_t	 numberOfPerceivedObjects;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CpmParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CpmParameters;
extern asn_SEQUENCE_specifics_t asn_SPC_CpmParameters_specs_1;
extern asn_TYPE_member_t asn_MBR_CpmParameters_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "StationDataContainer.h"
#include "SensorInformationContainer.h"
#include "PerceivedObjectContainer.h"
#include "FreeSpaceAddendumContainer.h"

#endif	/* _CpmParameters_H_ */
#include "asn_internal.h"
