/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "ITS-Container.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_DeltaReferencePositionV1_H_
#define	_DeltaReferencePositionV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "DeltaLatitudeV1.h"
#include "DeltaLongitudeV1.h"
#include "DeltaAltitudeV1.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DeltaReferencePositionV1 */
typedef struct DeltaReferencePositionV1 {
	DeltaLatitudeV1_t	 deltaLatitude;
	DeltaLongitudeV1_t	 deltaLongitude;
	DeltaAltitudeV1_t	 deltaAltitude;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DeltaReferencePositionV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DeltaReferencePositionV1;
extern asn_SEQUENCE_specifics_t asn_SPC_DeltaReferencePositionV1_specs_1;
extern asn_TYPE_member_t asn_MBR_DeltaReferencePositionV1_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _DeltaReferencePositionV1_H_ */
#include "asn_internal.h"
