/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "/home/carlosrisma/IVIM ASN1 files/asn1_IS_ISO_TS_19321_IVI.asn"
 * 	`asn1c -fincludes-quoted`
 */

#ifndef	_EDT_H_
#define	_EDT_H_


#include "asn_application.h"

/* Including external dependencies */
#include "DTM.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EDT */
typedef DTM_t	 EDT_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EDT;
asn_struct_free_f EDT_free;
asn_struct_print_f EDT_print;
asn_constr_check_f EDT_constraint;
ber_type_decoder_f EDT_decode_ber;
der_type_encoder_f EDT_encode_der;
xer_type_decoder_f EDT_decode_xer;
xer_type_encoder_f EDT_encode_xer;
oer_type_decoder_f EDT_decode_oer;
oer_type_encoder_f EDT_encode_oer;
per_type_decoder_f EDT_decode_uper;
per_type_encoder_f EDT_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EDT_H_ */
#include "asn_internal.h"
