/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "/home/carlosrisma/IVIM ASN1 files/asn1_IS_ISO_TS_14906_EfcDsrcApplication.asn"
 * 	`asn1c -fincludes-quoted`
 */

#ifndef	_EFC_StationType_H_
#define	_EFC_StationType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EFC_StationType {
	EFC_StationType_unspecified	= 0,
	EFC_StationType_closedEntryWithPayment	= 1,
	EFC_StationType_closedEntryWithoutPayment	= 2,
	EFC_StationType_closedTransit	= 3,
	EFC_StationType_closedExit	= 4,
	EFC_StationType_closedCredit	= 5,
	EFC_StationType_mixed	= 6,
	EFC_StationType_passage	= 7,
	EFC_StationType_checkpoint	= 8,
	EFC_StationType_reload	= 9,
	EFC_StationType_reservedForFutureCENUse1	= 10,
	EFC_StationType_reservedForFutureCENUse2	= 11,
	EFC_StationType_reservedForFutureCENUse3	= 12,
	EFC_StationType_reservedForFutureCENUse4	= 13,
	EFC_StationType_privateUse5	= 14,
	EFC_StationType_privateUse6	= 15
} e_EFC_StationType;

/* EFC-StationType */
typedef long	 EFC_StationType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_EFC_StationType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_EFC_StationType;
extern const asn_INTEGER_specifics_t asn_SPC_EFC_StationType_specs_1;
asn_struct_free_f EFC_StationType_free;
asn_struct_print_f EFC_StationType_print;
asn_constr_check_f EFC_StationType_constraint;
ber_type_decoder_f EFC_StationType_decode_ber;
der_type_encoder_f EFC_StationType_encode_der;
xer_type_decoder_f EFC_StationType_decode_xer;
xer_type_encoder_f EFC_StationType_encode_xer;
oer_type_decoder_f EFC_StationType_decode_oer;
oer_type_encoder_f EFC_StationType_encode_oer;
per_type_decoder_f EFC_StationType_decode_uper;
per_type_encoder_f EFC_StationType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EFC_StationType_H_ */
#include "asn_internal.h"
