/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "ETSI-ITS-CDD.asn"
 */

#ifndef	_GeneralizedLanePosition_H_
#define	_GeneralizedLanePosition_H_


#include "asn_application.h"

/* Including external dependencies */
#include "LanePosition.h"
#include "LanePositionAndType.h"
#include "TrafficIslandPosition.h"
#include "MapPosition.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GeneralizedLanePosition_PR {
	GeneralizedLanePosition_PR_NOTHING,	/* No components present */
	GeneralizedLanePosition_PR_trafficLanePosition,
	GeneralizedLanePosition_PR_nonTrafficLanePosition,
	GeneralizedLanePosition_PR_trafficIslandPosition,
	GeneralizedLanePosition_PR_mapPosition
	/* Extensions may appear below */
	
} GeneralizedLanePosition_PR;

/* GeneralizedLanePosition */
typedef struct GeneralizedLanePosition {
	GeneralizedLanePosition_PR present;
	union GeneralizedLanePosition_u {
		LanePosition_t	 trafficLanePosition;
		LanePositionAndType_t	 nonTrafficLanePosition;
		TrafficIslandPosition_t	 trafficIslandPosition;
		MapPosition_t	 mapPosition;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GeneralizedLanePosition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GeneralizedLanePosition;
extern asn_CHOICE_specifics_t asn_SPC_GeneralizedLanePosition_specs_1;
extern asn_TYPE_member_t asn_MBR_GeneralizedLanePosition_1[4];
extern asn_per_constraints_t asn_PER_type_GeneralizedLanePosition_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _GeneralizedLanePosition_H_ */
#include "asn_internal.h"
