/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in asn1/ISO19091.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_GenericLane_H_
#define	_GenericLane_H_


#include "asn_application.h"

/* Including external dependencies */
#include "LaneID.h"
#include "DescriptiveName.h"
#include "ApproachID.h"
#include "LaneAttributes.h"
#include "AllowedManeuvers.h"
#include "NodeListXY.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ConnectsToList;
struct OverlayLaneList;
struct Reg_GenericLane;

/* GenericLane */
typedef struct GenericLane {
	LaneID_t	 laneID;
	DescriptiveName_t	*name;	/* OPTIONAL */
	ApproachID_t	*ingressApproach;	/* OPTIONAL */
	ApproachID_t	*egressApproach;	/* OPTIONAL */
	LaneAttributes_t	 laneAttributes;
	AllowedManeuvers_t	*maneuvers;	/* OPTIONAL */
	NodeListXY_t	 nodeList;
	struct ConnectsToList	*connectsTo;	/* OPTIONAL */
	struct OverlayLaneList	*overlays;	/* OPTIONAL */
	struct GenericLane__regional {
		A_SEQUENCE_OF(struct Reg_GenericLane) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GenericLane_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GenericLane;
extern asn_SEQUENCE_specifics_t asn_SPC_GenericLane_specs_1;
extern asn_TYPE_member_t asn_MBR_GenericLane_1[10];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ConnectsToList.h"
#include "OverlayLaneList.h"
#include "RegionalExtension.h"

#endif	/* _GenericLane_H_ */
#include "asn_internal.h"
