/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "asn1/TS102894-2v131-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_HazardousLocation_DangerousCurveSubCauseCode_H_
#define	_HazardousLocation_DangerousCurveSubCauseCode_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HazardousLocation_DangerousCurveSubCauseCode {
	HazardousLocation_DangerousCurveSubCauseCode_unavailable	= 0,
	HazardousLocation_DangerousCurveSubCauseCode_dangerousLeftTurnCurve	= 1,
	HazardousLocation_DangerousCurveSubCauseCode_dangerousRightTurnCurve	= 2,
	HazardousLocation_DangerousCurveSubCauseCode_multipleCurvesStartingWithUnknownTurningDirection	= 3,
	HazardousLocation_DangerousCurveSubCauseCode_multipleCurvesStartingWithLeftTurn	= 4,
	HazardousLocation_DangerousCurveSubCauseCode_multipleCurvesStartingWithRightTurn	= 5
} e_HazardousLocation_DangerousCurveSubCauseCode;

/* HazardousLocation-DangerousCurveSubCauseCode */
typedef long	 HazardousLocation_DangerousCurveSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HazardousLocation_DangerousCurveSubCauseCode;
asn_struct_free_f HazardousLocation_DangerousCurveSubCauseCode_free;
asn_struct_print_f HazardousLocation_DangerousCurveSubCauseCode_print;
asn_constr_check_f HazardousLocation_DangerousCurveSubCauseCode_constraint;
ber_type_decoder_f HazardousLocation_DangerousCurveSubCauseCode_decode_ber;
der_type_encoder_f HazardousLocation_DangerousCurveSubCauseCode_encode_der;
xer_type_decoder_f HazardousLocation_DangerousCurveSubCauseCode_decode_xer;
xer_type_encoder_f HazardousLocation_DangerousCurveSubCauseCode_encode_xer;
jer_type_encoder_f HazardousLocation_DangerousCurveSubCauseCode_encode_jer;
oer_type_decoder_f HazardousLocation_DangerousCurveSubCauseCode_decode_oer;
oer_type_encoder_f HazardousLocation_DangerousCurveSubCauseCode_encode_oer;
per_type_decoder_f HazardousLocation_DangerousCurveSubCauseCode_decode_uper;
per_type_encoder_f HazardousLocation_DangerousCurveSubCauseCode_encode_uper;
per_type_decoder_f HazardousLocation_DangerousCurveSubCauseCode_decode_aper;
per_type_encoder_f HazardousLocation_DangerousCurveSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _HazardousLocation_DangerousCurveSubCauseCode_H_ */
#include "asn_internal.h"
