/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "asn1/TS102894-2v131-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_LongitudinalAccelerationValue_H_
#define	_LongitudinalAccelerationValue_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LongitudinalAccelerationValue {
	LongitudinalAccelerationValue_pointOneMeterPerSecSquaredForward	= 1,
	LongitudinalAccelerationValue_pointOneMeterPerSecSquaredBackward	= -1,
	LongitudinalAccelerationValue_unavailable	= 161
} e_LongitudinalAccelerationValue;

/* LongitudinalAccelerationValue */
typedef long	 LongitudinalAccelerationValue_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LongitudinalAccelerationValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LongitudinalAccelerationValue;
asn_struct_free_f LongitudinalAccelerationValue_free;
asn_struct_print_f LongitudinalAccelerationValue_print;
asn_constr_check_f LongitudinalAccelerationValue_constraint;
ber_type_decoder_f LongitudinalAccelerationValue_decode_ber;
der_type_encoder_f LongitudinalAccelerationValue_encode_der;
xer_type_decoder_f LongitudinalAccelerationValue_decode_xer;
xer_type_encoder_f LongitudinalAccelerationValue_encode_xer;
jer_type_encoder_f LongitudinalAccelerationValue_encode_jer;
oer_type_decoder_f LongitudinalAccelerationValue_decode_oer;
oer_type_encoder_f LongitudinalAccelerationValue_encode_oer;
per_type_decoder_f LongitudinalAccelerationValue_decode_uper;
per_type_encoder_f LongitudinalAccelerationValue_encode_uper;
per_type_decoder_f LongitudinalAccelerationValue_decode_aper;
per_type_encoder_f LongitudinalAccelerationValue_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _LongitudinalAccelerationValue_H_ */
#include "asn_internal.h"
