/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DENM-PDU-Descriptions"
 * 	found in "asn1/EN302637-3v131-DENM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ManagementContainer_H_
#define	_ManagementContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ActionID.h"
#include "TimestampIts.h"
#include "Termination.h"
#include "ReferencePosition.h"
#include "RelevanceDistance.h"
#include "RelevanceTrafficDirection.h"
#include "ValidityDuration.h"
#include "TransmissionInterval.h"
#include "StationType.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ManagementContainer */
typedef struct ManagementContainer {
	ActionID_t	 actionID;
	TimestampIts_t	 detectionTime;
	TimestampIts_t	 referenceTime;
	Termination_t	*termination;	/* OPTIONAL */
	ReferencePosition_t	 eventPosition;
	RelevanceDistance_t	*relevanceDistance;	/* OPTIONAL */
	RelevanceTrafficDirection_t	*relevanceTrafficDirection;	/* OPTIONAL */
	ValidityDuration_t	*validityDuration;	/* DEFAULT 600 */
	TransmissionInterval_t	*transmissionInterval;	/* OPTIONAL */
	StationType_t	 stationType;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ManagementContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ManagementContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_ManagementContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_ManagementContainer_1[10];

#ifdef __cplusplus
}
#endif

#endif	/* _ManagementContainer_H_ */
#include "asn_internal.h"
