/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "asn1/TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_OriginatingRSUContainer_H_
#define	_OriginatingRSUContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "IntersectionReferenceID.h"
#include "RoadSegmentReferenceID.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum OriginatingRSUContainer_PR {
	OriginatingRSUContainer_PR_NOTHING,	/* No components present */
	OriginatingRSUContainer_PR_intersectionReferenceId,
	OriginatingRSUContainer_PR_roadSegmentReferenceId
	/* Extensions may appear below */
	
} OriginatingRSUContainer_PR;

/* OriginatingRSUContainer */
typedef struct OriginatingRSUContainer {
	OriginatingRSUContainer_PR present;
	union OriginatingRSUContainer_u {
		IntersectionReferenceID_t	 intersectionReferenceId;
		RoadSegmentReferenceID_t	 roadSegmentReferenceId;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OriginatingRSUContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OriginatingRSUContainer;
extern asn_CHOICE_specifics_t asn_SPC_OriginatingRSUContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_OriginatingRSUContainer_1[2];
extern asn_per_constraints_t asn_PER_type_OriginatingRSUContainer_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _OriginatingRSUContainer_H_ */
#include "asn_internal.h"
