/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in asn1/ISO19321.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_PlatooningRule_H_
#define	_PlatooningRule_H_


#include "asn_application.h"

/* Including external dependencies */
#include "PriorityLevel.h"
#include "SaeAutomationLevels.h"
#include "MaxNoOfVehicles.h"
#include "MaxLenghtOfPlatoon.h"
#include "GapBetweenVehicles.h"
#include "SpeedValue.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RoadSignCodes;
struct ConstraintTextLines2;

/* PlatooningRule */
typedef struct PlatooningRule {
	PriorityLevel_t	 priority;
	SaeAutomationLevels_t	 allowedSaeAutomationLevels;
	MaxNoOfVehicles_t	*maxNoOfVehicles;	/* OPTIONAL */
	MaxLenghtOfPlatoon_t	*maxLenghtOfPlatoon;	/* OPTIONAL */
	GapBetweenVehicles_t	*minGapBetweenVehicles;	/* OPTIONAL */
	SpeedValue_t	*platoonMaxSpeedLimit;	/* OPTIONAL */
	SpeedValue_t	*platoonMinSpeedLimit;	/* OPTIONAL */
	SpeedValue_t	*platoonSpeedRecommendation;	/* OPTIONAL */
	struct RoadSignCodes	*roadSignCodes;	/* OPTIONAL */
	struct ConstraintTextLines2	*extraText;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PlatooningRule_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PlatooningRule;
extern asn_SEQUENCE_specifics_t asn_SPC_PlatooningRule_specs_1;
extern asn_TYPE_member_t asn_MBR_PlatooningRule_1[10];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RoadSignCodes.h"
#include "ConstraintTextLines2.h"

#endif	/* _PlatooningRule_H_ */
#include "asn_internal.h"
