/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "/home/carlosrisma/IVIM ASN1 files/asn1_IS_ISO_TS_19321_IVI.asn"
 * 	`asn1c -fincludes-quoted`
 */

#ifndef	_PMD_H_
#define	_PMD_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PMD {
	PMD_national_holiday	= 0,
	PMD_even_days	= 1,
	PMD_odd_days	= 2,
	PMD_market_day	= 3
} e_PMD;

/* PMD */
typedef BIT_STRING_t	 PMD_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PMD_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PMD;
asn_struct_free_f PMD_free;
asn_struct_print_f PMD_print;
asn_constr_check_f PMD_constraint;
ber_type_decoder_f PMD_decode_ber;
der_type_encoder_f PMD_encode_der;
xer_type_decoder_f PMD_decode_xer;
xer_type_encoder_f PMD_encode_xer;
oer_type_decoder_f PMD_decode_oer;
oer_type_encoder_f PMD_encode_oer;
per_type_decoder_f PMD_decode_uper;
per_type_encoder_f PMD_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PMD_H_ */
#include "asn_internal.h"
