/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "asn1/EN302637-2v141-CAM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_SafetyCarContainer_H_
#define	_SafetyCarContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "LightBarSirenInUse.h"
#include "TrafficRule.h"
#include "SpeedLimit.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CauseCode;

/* SafetyCarContainer */
typedef struct SafetyCarContainer {
	LightBarSirenInUse_t	 lightBarSirenInUse;
	struct CauseCode	*incidentIndication;	/* OPTIONAL */
	TrafficRule_t	*trafficRule;	/* OPTIONAL */
	SpeedLimit_t	*speedLimit;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SafetyCarContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SafetyCarContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_SafetyCarContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_SafetyCarContainer_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CauseCode.h"

#endif	/* _SafetyCarContainer_H_ */
#include "asn_internal.h"
