/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AVIAEINumberingAndDataStructures"
 * 	found in asn1/ISO14816.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ServiceApplicationLimit_H_
#define	_ServiceApplicationLimit_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ServiceApplicationLimit {
	ServiceApplicationLimit_notForPostpayment	= 0,
	ServiceApplicationLimit_notForPrepayment	= 1,
	ServiceApplicationLimit_notForVehicleaccess	= 2,
	ServiceApplicationLimit_notForFleetcontrol	= 3,
	ServiceApplicationLimit_issuerSpecificRestriction1	= 4,
	ServiceApplicationLimit_issuerSpecificRestriction2	= 5,
	ServiceApplicationLimit_issuerSpecificRestriction3	= 6,
	ServiceApplicationLimit_issuerSpecificRestriction4	= 7
} e_ServiceApplicationLimit;

/* ServiceApplicationLimit */
typedef BIT_STRING_t	 ServiceApplicationLimit_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ServiceApplicationLimit_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ServiceApplicationLimit;
asn_struct_free_f ServiceApplicationLimit_free;
asn_struct_print_f ServiceApplicationLimit_print;
asn_constr_check_f ServiceApplicationLimit_constraint;
ber_type_decoder_f ServiceApplicationLimit_decode_ber;
der_type_encoder_f ServiceApplicationLimit_encode_der;
xer_type_decoder_f ServiceApplicationLimit_decode_xer;
xer_type_encoder_f ServiceApplicationLimit_encode_xer;
jer_type_encoder_f ServiceApplicationLimit_encode_jer;
oer_type_decoder_f ServiceApplicationLimit_decode_oer;
oer_type_encoder_f ServiceApplicationLimit_encode_oer;
per_type_decoder_f ServiceApplicationLimit_decode_uper;
per_type_encoder_f ServiceApplicationLimit_encode_uper;
per_type_decoder_f ServiceApplicationLimit_decode_aper;
per_type_encoder_f ServiceApplicationLimit_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ServiceApplicationLimit_H_ */
#include "asn_internal.h"
