/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in asn1/ISO19091.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_SignalRequest_H_
#define	_SignalRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "IntersectionReferenceID.h"
#include "RequestID.h"
#include "PriorityRequestType.h"
#include "IntersectionAccessPoint.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct IntersectionAccessPoint;
struct Reg_SignalRequest;

/* SignalRequest */
typedef struct SignalRequest {
	IntersectionReferenceID_t	 id;
	RequestID_t	 requestID;
	PriorityRequestType_t	 requestType;
	IntersectionAccessPoint_t	 inBoundLane;
	struct IntersectionAccessPoint	*outBoundLane;	/* OPTIONAL */
	struct SignalRequest__regional {
		A_SEQUENCE_OF(struct Reg_SignalRequest) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignalRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignalRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_SignalRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_SignalRequest_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "IntersectionAccessPoint.h"
#include "RegionalExtension.h"

#endif	/* _SignalRequest_H_ */
#include "asn_internal.h"
