/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "asn1/TR103562v211-CPM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_TrailerData_H_
#define	_TrailerData_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RefPointId.h"
#include "HitchPointOffset.h"
#include "FrontOverhang.h"
#include "RearOverhang.h"
#include "VehicleWidth.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CartesianAngle;

/* TrailerData */
typedef struct TrailerData {
	RefPointId_t	 refPointId;
	HitchPointOffset_t	 hitchPointOffset;
	FrontOverhang_t	 frontOverhang;
	RearOverhang_t	 rearOverhang;
	VehicleWidth_t	*trailerWidth;	/* OPTIONAL */
	struct CartesianAngle	*hitchAngle;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TrailerData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TrailerData;
extern asn_SEQUENCE_specifics_t asn_SPC_TrailerData_specs_1;
extern asn_TYPE_member_t asn_MBR_TrailerData_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CartesianAngle.h"

#endif	/* _TrailerData_H_ */
#include "asn_internal.h"
