/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in asn1/ISO19321.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_VcClass_H_
#define	_VcClass_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VcClass {
	VcClass_classA	= 0,
	VcClass_classB	= 1,
	VcClass_classC	= 2,
	VcClass_classD	= 3,
	VcClass_classE	= 4,
	VcClass_classF	= 5,
	VcClass_classG	= 6,
	VcClass_classH	= 7
} e_VcClass;

/* VcClass */
typedef long	 VcClass_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_VcClass_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_VcClass;
asn_struct_free_f VcClass_free;
asn_struct_print_f VcClass_print;
asn_constr_check_f VcClass_constraint;
ber_type_decoder_f VcClass_decode_ber;
der_type_encoder_f VcClass_encode_der;
xer_type_decoder_f VcClass_decode_xer;
xer_type_encoder_f VcClass_encode_xer;
jer_type_encoder_f VcClass_encode_jer;
oer_type_decoder_f VcClass_decode_oer;
oer_type_encoder_f VcClass_encode_oer;
per_type_decoder_f VcClass_decode_uper;
per_type_encoder_f VcClass_encode_uper;
per_type_decoder_f VcClass_decode_aper;
per_type_encoder_f VcClass_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _VcClass_H_ */
#include "asn_internal.h"
