/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in asn1/ISO14906-0-6.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_VehicleAxles_H_
#define	_VehicleAxles_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Int1.h"
#include "NativeEnumerated.h"
#include "TrailerAxles.h"
#include "TractorAxles.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VehicleAxles__vehicleAxlesNumber__tyreType {
	VehicleAxles__vehicleAxlesNumber__tyreType_notSpecified	= 0,
	VehicleAxles__vehicleAxlesNumber__tyreType_singleTyre	= 1,
	VehicleAxles__vehicleAxlesNumber__tyreType_dualTyres	= 2,
	VehicleAxles__vehicleAxlesNumber__tyreType_reservedForUse	= 3
} e_VehicleAxles__vehicleAxlesNumber__tyreType;

/* VehicleAxles */
typedef struct VehicleAxles {
	Int1_t	 vehicleFirstAxleHeight;
	struct VehicleAxles__vehicleAxlesNumber {
		long	 tyreType;
		struct VehicleAxles__vehicleAxlesNumber__numberOfAxles {
			TrailerAxles_t	 trailerAxles;
			TractorAxles_t	 tractorAxles;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} numberOfAxles;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} vehicleAxlesNumber;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleAxles_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_tyreType_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_VehicleAxles;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleAxles_H_ */
#include "asn_internal.h"
