/* ============================================================================
 * Research Project: Data communication in the environment of
intelligent cars
 * Author: Kirill Komarov
 * Date: 2026
 * 
 * Description:
 * This file contains source code developed (or modified) as part of the 
 * research for the paper: "Data communication in the environment of
intelligent cars".
 * 
 * DISCLAIMER & ACKNOWLEDGEMENT:
 * Please note that this file contains or may contain code fragments, 
 * algorithms, or architectural solutions that were previously implemented 
 * in the "VaN3Twin" project https://github.com/DriveX-devs/VaN3Twin.git.
 * 
 * The borrowed code has been adapted and is used strictly for academic 
 * and research purposes. All rights to the original code segments belong 
 * to their respective original authors.
 * ============================================================================ */
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "ETSI-ITS-CDD.asn"
 */

#ifndef	_VruClusterInformation_H_
#define	_VruClusterInformation_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Identifier1B.h"
#include "CardinalNumber1B.h"
#include "VruClusterProfiles.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Shape;

/* VruClusterInformation */
typedef struct VruClusterInformation {
	Identifier1B_t	*clusterId	/* OPTIONAL */;
	struct Shape	*clusterBoundingBoxShape	/* OPTIONAL */;
	CardinalNumber1B_t	 clusterCardinalitySize;
	VruClusterProfiles_t	*clusterProfiles	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VruClusterInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VruClusterInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_VruClusterInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_VruClusterInformation_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Shape.h"

#endif	/* _VruClusterInformation_H_ */
#include "asn_internal.h"
