/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_AccelerationMagnitude_H_
#define	_AccelerationMagnitude_H_


#include "asn_application.h"

/* Including external dependencies */
#include "AccelerationMagnitudeValue.h"
#include "AccelerationConfidence.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AccelerationMagnitude */
typedef struct AccelerationMagnitude {
	AccelerationMagnitudeValue_t	 accelerationMagnitudeValue;
	AccelerationConfidence_t	 accelerationConfidence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AccelerationMagnitude_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AccelerationMagnitude;

#ifdef __cplusplus
}
#endif

#endif	/* _AccelerationMagnitude_H_ */
#include "asn_internal.h"
