/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_Acceleration3dWithConfidence_H_
#define	_Acceleration3dWithConfidence_H_


#include "asn_application.h"

/* Including external dependencies */
#include "AccelerationPolarWithZ.h"
#include "AccelerationCartesian.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Acceleration3dWithConfidence_PR {
	Acceleration3dWithConfidence_PR_NOTHING,	/* No components present */
	Acceleration3dWithConfidence_PR_polarAcceleration,
	Acceleration3dWithConfidence_PR_cartesianAcceleration
} Acceleration3dWithConfidence_PR;

/* Acceleration3dWithConfidence */
typedef struct Acceleration3dWithConfidence {
	Acceleration3dWithConfidence_PR present;
	union Acceleration3dWithConfidence_u {
		AccelerationPolarWithZ_t	 polarAcceleration;
		AccelerationCartesian_t	 cartesianAcceleration;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Acceleration3dWithConfidence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Acceleration3dWithConfidence;

#ifdef __cplusplus
}
#endif

#endif	/* _Acceleration3dWithConfidence_H_ */
#include "asn_internal.h"
