/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_AccelerationCartesian_H_
#define	_AccelerationCartesian_H_


#include "asn_application.h"

/* Including external dependencies */
#include "AccelerationComponent.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AccelerationComponent;

/* AccelerationCartesian */
typedef struct AccelerationCartesian {
	AccelerationComponent_t	 xAcceleration;
	AccelerationComponent_t	 yAcceleration;
	struct AccelerationComponent	*zAcceleration	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AccelerationCartesian_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AccelerationCartesian;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AccelerationComponent.h"

#endif	/* _AccelerationCartesian_H_ */
#include "asn_internal.h"
