/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_AccelerationComponent_H_
#define	_AccelerationComponent_H_


#include "asn_application.h"

/* Including external dependencies */
#include "AccelerationValue.h"
#include "AccelerationConfidence.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AccelerationComponent */
typedef struct AccelerationComponent {
	AccelerationValue_t	 value;
	AccelerationConfidence_t	 confidence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AccelerationComponent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AccelerationComponent;

#ifdef __cplusplus
}
#endif

#endif	/* _AccelerationComponent_H_ */
#include "asn_internal.h"
