/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_AccelerationMagnitudeValue_H_
#define	_AccelerationMagnitudeValue_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AccelerationMagnitudeValue {
	AccelerationMagnitudeValue_positiveOutOfRange	= 160,
	AccelerationMagnitudeValue_unavailable	= 161
} e_AccelerationMagnitudeValue;

/* AccelerationMagnitudeValue */
typedef long	 AccelerationMagnitudeValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AccelerationMagnitudeValue;
asn_struct_free_f AccelerationMagnitudeValue_free;
asn_struct_print_f AccelerationMagnitudeValue_print;
asn_constr_check_f AccelerationMagnitudeValue_constraint;
ber_type_decoder_f AccelerationMagnitudeValue_decode_ber;
der_type_encoder_f AccelerationMagnitudeValue_encode_der;
xer_type_decoder_f AccelerationMagnitudeValue_decode_xer;
xer_type_encoder_f AccelerationMagnitudeValue_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AccelerationMagnitudeValue_H_ */
#include "asn_internal.h"
