/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_AdvisedTrrContainer_H_
#define	_AdvisedTrrContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TrrDescription.h"
#include "TemporalCharacteristics.h"
#include "KinematicsCharacteristics.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AdvisedTrrContainer */
typedef struct AdvisedTrrContainer {
	TrrDescription_t	 trrDescription;
	TemporalCharacteristics_t	 temporalCharacteristics;
	KinematicsCharacteristics_t	*kinematicsCharacteristics	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AdvisedTrrContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AdvisedTrrContainer;

#ifdef __cplusplus
}
#endif

#endif	/* _AdvisedTrrContainer_H_ */
#include "asn_internal.h"
