/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_AngleConfidence_H_
#define	_AngleConfidence_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AngleConfidence {
	AngleConfidence_outOfRange	= 126,
	AngleConfidence_unavailable	= 127
} e_AngleConfidence;

/* AngleConfidence */
typedef long	 AngleConfidence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AngleConfidence;
asn_struct_free_f AngleConfidence_free;
asn_struct_print_f AngleConfidence_print;
asn_constr_check_f AngleConfidence_constraint;
ber_type_decoder_f AngleConfidence_decode_ber;
der_type_encoder_f AngleConfidence_encode_der;
xer_type_decoder_f AngleConfidence_decode_xer;
xer_type_encoder_f AngleConfidence_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AngleConfidence_H_ */
#include "asn_internal.h"
