/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_AngularAccelerationConfidence_H_
#define	_AngularAccelerationConfidence_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AngularAccelerationConfidence {
	AngularAccelerationConfidence_degSecSquared_01	= 0,
	AngularAccelerationConfidence_degSecSquared_02	= 1,
	AngularAccelerationConfidence_degSecSquared_05	= 2,
	AngularAccelerationConfidence_degSecSquared_10	= 3,
	AngularAccelerationConfidence_degSecSquared_20	= 4,
	AngularAccelerationConfidence_degSecSquared_50	= 5,
	AngularAccelerationConfidence_outOfRange	= 6,
	AngularAccelerationConfidence_unavailable	= 7
} e_AngularAccelerationConfidence;

/* AngularAccelerationConfidence */
typedef long	 AngularAccelerationConfidence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AngularAccelerationConfidence;
asn_struct_free_f AngularAccelerationConfidence_free;
asn_struct_print_f AngularAccelerationConfidence_print;
asn_constr_check_f AngularAccelerationConfidence_constraint;
ber_type_decoder_f AngularAccelerationConfidence_decode_ber;
der_type_encoder_f AngularAccelerationConfidence_encode_der;
xer_type_decoder_f AngularAccelerationConfidence_decode_xer;
xer_type_encoder_f AngularAccelerationConfidence_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AngularAccelerationConfidence_H_ */
#include "asn_internal.h"
