/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_ConfidenceLevel_H_
#define	_ConfidenceLevel_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ConfidenceLevel {
	ConfidenceLevel_unavailable	= 101
} e_ConfidenceLevel;

/* ConfidenceLevel */
typedef long	 ConfidenceLevel_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConfidenceLevel;
asn_struct_free_f ConfidenceLevel_free;
asn_struct_print_f ConfidenceLevel_print;
asn_constr_check_f ConfidenceLevel_constraint;
ber_type_decoder_f ConfidenceLevel_decode_ber;
der_type_encoder_f ConfidenceLevel_encode_der;
xer_type_decoder_f ConfidenceLevel_decode_xer;
xer_type_encoder_f ConfidenceLevel_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ConfidenceLevel_H_ */
#include "asn_internal.h"
