/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_CorrelationColumn_H_
#define	_CorrelationColumn_H_


#include "asn_application.h"

/* Including external dependencies */
#include "CorrelationCellValue.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CorrelationColumn */
typedef struct CorrelationColumn {
	A_SEQUENCE_OF(CorrelationCellValue_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CorrelationColumn_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CorrelationColumn;

#ifdef __cplusplus
}
#endif

#endif	/* _CorrelationColumn_H_ */
#include "asn_internal.h"
