/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_CurrentStateAdvisedChange_H_
#define	_CurrentStateAdvisedChange_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"
#include "NativeInteger.h"
#include "JoinGroupStateChange.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CurrentStateAdvisedChange_PR {
	CurrentStateAdvisedChange_PR_NOTHING,	/* No components present */
	CurrentStateAdvisedChange_PR_transitToHumanDrivingMode,
	CurrentStateAdvisedChange_PR_transitToAutomatedDrivingMode,
	CurrentStateAdvisedChange_PR_followMeWithMinTimeInterDistance,
	CurrentStateAdvisedChange_PR_joinGroup,
	CurrentStateAdvisedChange_PR_leaveGroup,
	CurrentStateAdvisedChange_PR_emergencyBrakeTriggering,
	CurrentStateAdvisedChange_PR_stayInLane,
	CurrentStateAdvisedChange_PR_stop,
	CurrentStateAdvisedChange_PR_resetStop,
	CurrentStateAdvisedChange_PR_resetStayInLane,
	CurrentStateAdvisedChange_PR_stayAwayOfVehicleSithStationID,
	CurrentStateAdvisedChange_PR_resetStayAwayOfVehicle
} CurrentStateAdvisedChange_PR;

/* CurrentStateAdvisedChange */
typedef struct CurrentStateAdvisedChange {
	CurrentStateAdvisedChange_PR present;
	union CurrentStateAdvisedChange_u {
		NULL_t	 transitToHumanDrivingMode;
		NULL_t	 transitToAutomatedDrivingMode;
		long	 followMeWithMinTimeInterDistance;
		JoinGroupStateChange_t	 joinGroup;
		NULL_t	 leaveGroup;
		NULL_t	 emergencyBrakeTriggering;
		NULL_t	 stayInLane;
		NULL_t	 stop;
		NULL_t	 resetStop;
		NULL_t	 resetStayInLane;
		NULL_t	 stayAwayOfVehicleSithStationID;
		NULL_t	 resetStayAwayOfVehicle;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CurrentStateAdvisedChange_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CurrentStateAdvisedChange;

#ifdef __cplusplus
}
#endif

#endif	/* _CurrentStateAdvisedChange_H_ */
#include "asn_internal.h"
