/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#include "CurrentStateAdvisedChange.h"

static int
memb_followMeWithMinTimeInterDistance_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 300 && value <= 2000)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_CurrentStateAdvisedChange_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CurrentStateAdvisedChange, choice.transitToHumanDrivingMode),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"transitToHumanDrivingMode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CurrentStateAdvisedChange, choice.transitToAutomatedDrivingMode),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"transitToAutomatedDrivingMode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CurrentStateAdvisedChange, choice.followMeWithMinTimeInterDistance),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_followMeWithMinTimeInterDistance_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"followMeWithMinTimeInterDistance"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CurrentStateAdvisedChange, choice.joinGroup),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_JoinGroupStateChange,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"joinGroup"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CurrentStateAdvisedChange, choice.leaveGroup),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"leaveGroup"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CurrentStateAdvisedChange, choice.emergencyBrakeTriggering),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"emergencyBrakeTriggering"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CurrentStateAdvisedChange, choice.stayInLane),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"stayInLane"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CurrentStateAdvisedChange, choice.stop),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"stop"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CurrentStateAdvisedChange, choice.resetStop),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"resetStop"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CurrentStateAdvisedChange, choice.resetStayInLane),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"resetStayInLane"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CurrentStateAdvisedChange, choice.stayAwayOfVehicleSithStationID),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"stayAwayOfVehicleSithStationID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CurrentStateAdvisedChange, choice.resetStayAwayOfVehicle),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"resetStayAwayOfVehicle"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_CurrentStateAdvisedChange_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* transitToHumanDrivingMode */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* transitToAutomatedDrivingMode */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* followMeWithMinTimeInterDistance */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* joinGroup */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* leaveGroup */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* emergencyBrakeTriggering */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* stayInLane */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* stop */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* resetStop */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* resetStayInLane */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* stayAwayOfVehicleSithStationID */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 } /* resetStayAwayOfVehicle */
};
static asn_CHOICE_specifics_t asn_SPC_CurrentStateAdvisedChange_specs_1 = {
	sizeof(struct CurrentStateAdvisedChange),
	offsetof(struct CurrentStateAdvisedChange, _asn_ctx),
	offsetof(struct CurrentStateAdvisedChange, present),
	sizeof(((struct CurrentStateAdvisedChange *)0)->present),
	asn_MAP_CurrentStateAdvisedChange_tag2el_1,
	12,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_CurrentStateAdvisedChange = {
	"CurrentStateAdvisedChange",
	"CurrentStateAdvisedChange",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_CurrentStateAdvisedChange_1,
	12,	/* Elements count */
	&asn_SPC_CurrentStateAdvisedChange_specs_1	/* Additional specs */
};

