/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_DeltaTimeQuarterSecond_H_
#define	_DeltaTimeQuarterSecond_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DeltaTimeQuarterSecond {
	DeltaTimeQuarterSecond_unavailable	= 255
} e_DeltaTimeQuarterSecond;

/* DeltaTimeQuarterSecond */
typedef long	 DeltaTimeQuarterSecond_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DeltaTimeQuarterSecond;
asn_struct_free_f DeltaTimeQuarterSecond_free;
asn_struct_print_f DeltaTimeQuarterSecond_print;
asn_constr_check_f DeltaTimeQuarterSecond_constraint;
ber_type_decoder_f DeltaTimeQuarterSecond_decode_ber;
der_type_encoder_f DeltaTimeQuarterSecond_encode_der;
xer_type_decoder_f DeltaTimeQuarterSecond_decode_xer;
xer_type_encoder_f DeltaTimeQuarterSecond_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DeltaTimeQuarterSecond_H_ */
#include "asn_internal.h"
