/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_EventZone_H_
#define	_EventZone_H_


#include "asn_application.h"

/* Including external dependencies */
#include "EventHistory.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EventZone */
typedef EventHistory_t	 EventZone_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EventZone;
asn_struct_free_f EventZone_free;
asn_struct_print_f EventZone_print;
asn_constr_check_f EventZone_constraint;
ber_type_decoder_f EventZone_decode_ber;
der_type_encoder_f EventZone_encode_der;
xer_type_decoder_f EventZone_decode_xer;
xer_type_encoder_f EventZone_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _EventZone_H_ */
#include "asn_internal.h"
