/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_InterferenceManagementChannel_H_
#define	_InterferenceManagementChannel_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* InterferenceManagementChannel */
typedef struct InterferenceManagementChannel {
	long	 centreFrequency;
	long	 channelWidth;
	long	 exponent;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InterferenceManagementChannel_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InterferenceManagementChannel;

#ifdef __cplusplus
}
#endif

#endif	/* _InterferenceManagementChannel_H_ */
#include "asn_internal.h"
