/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#include "InterferenceManagementInfoPerChannel.h"

static asn_TYPE_member_t asn_MBR_InterferenceManagementInfoPerChannel_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct InterferenceManagementInfoPerChannel, interferenceManagementChannel),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InterferenceManagementChannel,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"interferenceManagementChannel"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InterferenceManagementInfoPerChannel, interferenceManagementZoneType),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InterferenceManagementZoneType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"interferenceManagementZoneType"
		},
	{ ATF_POINTER, 2, offsetof(struct InterferenceManagementInfoPerChannel, interferenceManagementMitigationType),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MitigationForTechnologies,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"interferenceManagementMitigationType"
		},
	{ ATF_POINTER, 1, offsetof(struct InterferenceManagementInfoPerChannel, expiryTime),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimestampIts,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"expiryTime"
		},
};
static const ber_tlv_tag_t asn_DEF_InterferenceManagementInfoPerChannel_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_InterferenceManagementInfoPerChannel_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* interferenceManagementChannel */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* interferenceManagementZoneType */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* interferenceManagementMitigationType */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* expiryTime */
};
static asn_SEQUENCE_specifics_t asn_SPC_InterferenceManagementInfoPerChannel_specs_1 = {
	sizeof(struct InterferenceManagementInfoPerChannel),
	offsetof(struct InterferenceManagementInfoPerChannel, _asn_ctx),
	asn_MAP_InterferenceManagementInfoPerChannel_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* Start extensions */
	5	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_InterferenceManagementInfoPerChannel = {
	"InterferenceManagementInfoPerChannel",
	"InterferenceManagementInfoPerChannel",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_InterferenceManagementInfoPerChannel_tags_1,
	sizeof(asn_DEF_InterferenceManagementInfoPerChannel_tags_1)
		/sizeof(asn_DEF_InterferenceManagementInfoPerChannel_tags_1[0]), /* 1 */
	asn_DEF_InterferenceManagementInfoPerChannel_tags_1,	/* Same as above */
	sizeof(asn_DEF_InterferenceManagementInfoPerChannel_tags_1)
		/sizeof(asn_DEF_InterferenceManagementInfoPerChannel_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_InterferenceManagementInfoPerChannel_1,
	4,	/* Elements count */
	&asn_SPC_InterferenceManagementInfoPerChannel_specs_1	/* Additional specs */
};

