/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#include "JoinGroupStateChange.h"

static int
memb_withMinTimeInterDistance_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 300 && value <= 2000)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_JoinGroupStateChange_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct JoinGroupStateChange, choice.vehicleSynchronization),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vehicleSynchronization"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct JoinGroupStateChange, choice.modeLong),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"modeLong"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct JoinGroupStateChange, choice.modeLatLeftLane),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"modeLatLeftLane"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct JoinGroupStateChange, choice.modeLatRightLane),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"modeLatRightLane"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct JoinGroupStateChange, choice.withMinTimeInterDistance),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_withMinTimeInterDistance_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"withMinTimeInterDistance"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_JoinGroupStateChange_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* vehicleSynchronization */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* modeLong */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* modeLatLeftLane */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* modeLatRightLane */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* withMinTimeInterDistance */
};
static asn_CHOICE_specifics_t asn_SPC_JoinGroupStateChange_specs_1 = {
	sizeof(struct JoinGroupStateChange),
	offsetof(struct JoinGroupStateChange, _asn_ctx),
	offsetof(struct JoinGroupStateChange, present),
	sizeof(((struct JoinGroupStateChange *)0)->present),
	asn_MAP_JoinGroupStateChange_tag2el_1,
	5,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_JoinGroupStateChange = {
	"JoinGroupStateChange",
	"JoinGroupStateChange",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_JoinGroupStateChange_1,
	5,	/* Elements count */
	&asn_SPC_JoinGroupStateChange_specs_1	/* Additional specs */
};

