/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_JoinGroupStateChange_H_
#define	_JoinGroupStateChange_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NULL.h"
#include "NativeInteger.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum JoinGroupStateChange_PR {
	JoinGroupStateChange_PR_NOTHING,	/* No components present */
	JoinGroupStateChange_PR_vehicleSynchronization,
	JoinGroupStateChange_PR_modeLong,
	JoinGroupStateChange_PR_modeLatLeftLane,
	JoinGroupStateChange_PR_modeLatRightLane,
	JoinGroupStateChange_PR_withMinTimeInterDistance
} JoinGroupStateChange_PR;

/* JoinGroupStateChange */
typedef struct JoinGroupStateChange {
	JoinGroupStateChange_PR present;
	union JoinGroupStateChange_u {
		NULL_t	 vehicleSynchronization;
		NULL_t	 modeLong;
		NULL_t	 modeLatLeftLane;
		NULL_t	 modeLatRightLane;
		long	 withMinTimeInterDistance;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} JoinGroupStateChange_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_JoinGroupStateChange;

#ifdef __cplusplus
}
#endif

#endif	/* _JoinGroupStateChange_H_ */
#include "asn_internal.h"
