/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_LowerTriangularPositiveSemidefiniteMatrices_H_
#define	_LowerTriangularPositiveSemidefiniteMatrices_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LowerTriangularPositiveSemidefiniteMatrix;

/* LowerTriangularPositiveSemidefiniteMatrices */
typedef struct LowerTriangularPositiveSemidefiniteMatrices {
	A_SEQUENCE_OF(struct LowerTriangularPositiveSemidefiniteMatrix) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LowerTriangularPositiveSemidefiniteMatrices_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LowerTriangularPositiveSemidefiniteMatrices;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "LowerTriangularPositiveSemidefiniteMatrix.h"

#endif	/* _LowerTriangularPositiveSemidefiniteMatrices_H_ */
#include "asn_internal.h"
