/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_LowerTriangularPositiveSemidefiniteMatrix_H_
#define	_LowerTriangularPositiveSemidefiniteMatrix_H_


#include "asn_application.h"

/* Including external dependencies */
#include "MatrixIncludedComponents.h"
#include "LowerTriangularPositiveSemidefiniteMatrixColumns.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* LowerTriangularPositiveSemidefiniteMatrix */
typedef struct LowerTriangularPositiveSemidefiniteMatrix {
	MatrixIncludedComponents_t	 componentsIncludedIntheMatrix;
	LowerTriangularPositiveSemidefiniteMatrixColumns_t	 matrix;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LowerTriangularPositiveSemidefiniteMatrix_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LowerTriangularPositiveSemidefiniteMatrix;

#ifdef __cplusplus
}
#endif

#endif	/* _LowerTriangularPositiveSemidefiniteMatrix_H_ */
#include "asn_internal.h"
