/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_ManoeuvreAdviceContainer_H_
#define	_ManoeuvreAdviceContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ManoeuvreAdvice;

/* ManoeuvreAdviceContainer */
typedef struct ManoeuvreAdviceContainer {
	A_SEQUENCE_OF(struct ManoeuvreAdvice) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ManoeuvreAdviceContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ManoeuvreAdviceContainer;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ManoeuvreAdvice.h"

#endif	/* _ManoeuvreAdviceContainer_H_ */
#include "asn_internal.h"
