/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_ManoeuvreCooperationGoal_H_
#define	_ManoeuvreCooperationGoal_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ManoeuvreCooperationGoal {
	ManoeuvreCooperationGoal_vehicleInterception	= 0,
	ManoeuvreCooperationGoal_roadSafety	= 1,
	ManoeuvreCooperationGoal_humanHelth	= 2,
	ManoeuvreCooperationGoal_emergencyIntervention	= 3,
	ManoeuvreCooperationGoal_roadOperatorIntervention	= 4,
	ManoeuvreCooperationGoal_localTrafficManagement	= 5,
	ManoeuvreCooperationGoal_globalTrafficManagement	= 6
} e_ManoeuvreCooperationGoal;

/* ManoeuvreCooperationGoal */
typedef long	 ManoeuvreCooperationGoal_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ManoeuvreCooperationGoal;
asn_struct_free_f ManoeuvreCooperationGoal_free;
asn_struct_print_f ManoeuvreCooperationGoal_print;
asn_constr_check_f ManoeuvreCooperationGoal_constraint;
ber_type_decoder_f ManoeuvreCooperationGoal_decode_ber;
der_type_encoder_f ManoeuvreCooperationGoal_encode_der;
xer_type_decoder_f ManoeuvreCooperationGoal_decode_xer;
xer_type_encoder_f ManoeuvreCooperationGoal_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ManoeuvreCooperationGoal_H_ */
#include "asn_internal.h"
