/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_McmGenericCurentStateContainer_H_
#define	_McmGenericCurentStateContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "McmType.h"
#include "ManoeuvreId.h"
#include "ManoeuvreCoordinationConcept.h"
#include "ManoeuvreExecutionStatus.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ManoeuvreCoordinationRational;

/* McmGenericCurentStateContainer */
typedef struct McmGenericCurentStateContainer {
	McmType_t	 mcmType;
	ManoeuvreId_t	 manoeuvreId;
	ManoeuvreCoordinationConcept_t	 concept;
	struct ManoeuvreCoordinationRational	*rational	/* OPTIONAL */;
	ManoeuvreExecutionStatus_t	*executionStatus	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} McmGenericCurentStateContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_McmGenericCurentStateContainer;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ManoeuvreCoordinationRational.h"

#endif	/* _McmGenericCurentStateContainer_H_ */
#include "asn_internal.h"
