/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_McmStationType_H_
#define	_McmStationType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum McmStationType {
	McmStationType_vruPortableDevice	= 0,
	McmStationType_vehicle	= 1,
	McmStationType_roadsideUnit	= 2,
	McmStationType_centralStation	= 3
	/*
	 * Enumeration is extensible
	 */
} e_McmStationType;

/* McmStationType */
typedef long	 McmStationType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_McmStationType;
asn_struct_free_f McmStationType_free;
asn_struct_print_f McmStationType_print;
asn_constr_check_f McmStationType_constraint;
ber_type_decoder_f McmStationType_decode_ber;
der_type_encoder_f McmStationType_encode_der;
xer_type_decoder_f McmStationType_decode_xer;
xer_type_encoder_f McmStationType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _McmStationType_H_ */
#include "asn_internal.h"
