/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#include "MitigationPerTechnologyClass.h"

static int
memb_lowDutyCycle_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 10000)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_powerReduction_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 30)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_dmcToffLimit_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 1200)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_dmcTonLimit_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 20)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_MitigationPerTechnologyClass_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MitigationPerTechnologyClass, accessTechnologyClass),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AccessTechnologyClass,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"accessTechnologyClass"
		},
	{ ATF_POINTER, 4, offsetof(struct MitigationPerTechnologyClass, lowDutyCycle),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_lowDutyCycle_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"lowDutyCycle"
		},
	{ ATF_POINTER, 3, offsetof(struct MitigationPerTechnologyClass, powerReduction),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_powerReduction_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"powerReduction"
		},
	{ ATF_POINTER, 2, offsetof(struct MitigationPerTechnologyClass, dmcToffLimit),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_dmcToffLimit_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dmcToffLimit"
		},
	{ ATF_POINTER, 1, offsetof(struct MitigationPerTechnologyClass, dmcTonLimit),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_dmcTonLimit_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dmcTonLimit"
		},
};
static const ber_tlv_tag_t asn_DEF_MitigationPerTechnologyClass_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MitigationPerTechnologyClass_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* accessTechnologyClass */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* lowDutyCycle */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* powerReduction */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* dmcToffLimit */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* dmcTonLimit */
};
static asn_SEQUENCE_specifics_t asn_SPC_MitigationPerTechnologyClass_specs_1 = {
	sizeof(struct MitigationPerTechnologyClass),
	offsetof(struct MitigationPerTechnologyClass, _asn_ctx),
	asn_MAP_MitigationPerTechnologyClass_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	4,	/* Start extensions */
	6	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_MitigationPerTechnologyClass = {
	"MitigationPerTechnologyClass",
	"MitigationPerTechnologyClass",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_MitigationPerTechnologyClass_tags_1,
	sizeof(asn_DEF_MitigationPerTechnologyClass_tags_1)
		/sizeof(asn_DEF_MitigationPerTechnologyClass_tags_1[0]), /* 1 */
	asn_DEF_MitigationPerTechnologyClass_tags_1,	/* Same as above */
	sizeof(asn_DEF_MitigationPerTechnologyClass_tags_1)
		/sizeof(asn_DEF_MitigationPerTechnologyClass_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_MitigationPerTechnologyClass_1,
	5,	/* Elements count */
	&asn_SPC_MitigationPerTechnologyClass_specs_1	/* Additional specs */
};

