/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_OrdinalNumber3b_H_
#define	_OrdinalNumber3b_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* OrdinalNumber3b */
typedef long	 OrdinalNumber3b_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OrdinalNumber3b;
asn_struct_free_f OrdinalNumber3b_free;
asn_struct_print_f OrdinalNumber3b_print;
asn_constr_check_f OrdinalNumber3b_constraint;
ber_type_decoder_f OrdinalNumber3b_decode_ber;
der_type_encoder_f OrdinalNumber3b_encode_der;
xer_type_decoder_f OrdinalNumber3b_decode_xer;
xer_type_encoder_f OrdinalNumber3b_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _OrdinalNumber3b_H_ */
#include "asn_internal.h"
