/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#include "PolygonalShape.h"

static int
memb_polygon_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 3 && size <= 16)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_PolygonalShape_1[] = {
	{ ATF_POINTER, 1, offsetof(struct PolygonalShape, shapeReferencePoint),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CartesianPosition3d,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"shapeReferencePoint"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PolygonalShape, polygon),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SequenceOfCartesianPosition3d,
		memb_polygon_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"polygon"
		},
	{ ATF_POINTER, 1, offsetof(struct PolygonalShape, height),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_StandardLength12b,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"height"
		},
};
static const ber_tlv_tag_t asn_DEF_PolygonalShape_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PolygonalShape_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* shapeReferencePoint */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* polygon */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* height */
};
static asn_SEQUENCE_specifics_t asn_SPC_PolygonalShape_specs_1 = {
	sizeof(struct PolygonalShape),
	offsetof(struct PolygonalShape, _asn_ctx),
	asn_MAP_PolygonalShape_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PolygonalShape = {
	"PolygonalShape",
	"PolygonalShape",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PolygonalShape_tags_1,
	sizeof(asn_DEF_PolygonalShape_tags_1)
		/sizeof(asn_DEF_PolygonalShape_tags_1[0]), /* 1 */
	asn_DEF_PolygonalShape_tags_1,	/* Same as above */
	sizeof(asn_DEF_PolygonalShape_tags_1)
		/sizeof(asn_DEF_PolygonalShape_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_PolygonalShape_1,
	3,	/* Elements count */
	&asn_SPC_PolygonalShape_specs_1	/* Additional specs */
};

