/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_PositionConfidenceEllipse_H_
#define	_PositionConfidenceEllipse_H_


#include "asn_application.h"

/* Including external dependencies */
#include "SemiAxisLength.h"
#include "Wgs84AngleValue.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PositionConfidenceEllipse */
typedef struct PositionConfidenceEllipse {
	SemiAxisLength_t	 semiMajorAxisLength;
	SemiAxisLength_t	 semiMinorAxisLength;
	Wgs84AngleValue_t	 semiMajorAxisOrientation;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PositionConfidenceEllipse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PositionConfidenceEllipse;

#ifdef __cplusplus
}
#endif

#endif	/* _PositionConfidenceEllipse_H_ */
#include "asn_internal.h"
