/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#include "RadialShape.h"

static asn_TYPE_member_t asn_MBR_RadialShape_1[] = {
	{ ATF_POINTER, 1, offsetof(struct RadialShape, shapeReferencePoint),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CartesianPosition3d,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"shapeReferencePoint"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RadialShape, range),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_StandardLength12b,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"range"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RadialShape, stationaryHorizontalOpeningAngleStart),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Wgs84AngleValue,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"stationaryHorizontalOpeningAngleStart"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RadialShape, stationaryHorizontalOpeningAngleEnd),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Wgs84AngleValue,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"stationaryHorizontalOpeningAngleEnd"
		},
	{ ATF_POINTER, 2, offsetof(struct RadialShape, verticalOpeningAngleStart),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CartesianAngleValue,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"verticalOpeningAngleStart"
		},
	{ ATF_POINTER, 1, offsetof(struct RadialShape, verticalOpeningAngleEnd),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CartesianAngleValue,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"verticalOpeningAngleEnd"
		},
};
static const ber_tlv_tag_t asn_DEF_RadialShape_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RadialShape_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* shapeReferencePoint */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* range */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* stationaryHorizontalOpeningAngleStart */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* stationaryHorizontalOpeningAngleEnd */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* verticalOpeningAngleStart */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* verticalOpeningAngleEnd */
};
static asn_SEQUENCE_specifics_t asn_SPC_RadialShape_specs_1 = {
	sizeof(struct RadialShape),
	offsetof(struct RadialShape, _asn_ctx),
	asn_MAP_RadialShape_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_RadialShape = {
	"RadialShape",
	"RadialShape",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RadialShape_tags_1,
	sizeof(asn_DEF_RadialShape_tags_1)
		/sizeof(asn_DEF_RadialShape_tags_1[0]), /* 1 */
	asn_DEF_RadialShape_tags_1,	/* Same as above */
	sizeof(asn_DEF_RadialShape_tags_1)
		/sizeof(asn_DEF_RadialShape_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_RadialShape_1,
	6,	/* Elements count */
	&asn_SPC_RadialShape_specs_1	/* Additional specs */
};

