/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_RailwayLevelCrossingSubCauseCode_H_
#define	_RailwayLevelCrossingSubCauseCode_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RailwayLevelCrossingSubCauseCode {
	RailwayLevelCrossingSubCauseCode_unavailable	= 0,
	RailwayLevelCrossingSubCauseCode_doNotCrossAbnormalSituation	= 1,
	RailwayLevelCrossingSubCauseCode_closed	= 2,
	RailwayLevelCrossingSubCauseCode_unguarded	= 3,
	RailwayLevelCrossingSubCauseCode_nominal	= 4
} e_RailwayLevelCrossingSubCauseCode;

/* RailwayLevelCrossingSubCauseCode */
typedef long	 RailwayLevelCrossingSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RailwayLevelCrossingSubCauseCode;
asn_struct_free_f RailwayLevelCrossingSubCauseCode_free;
asn_struct_print_f RailwayLevelCrossingSubCauseCode_print;
asn_constr_check_f RailwayLevelCrossingSubCauseCode_constraint;
ber_type_decoder_f RailwayLevelCrossingSubCauseCode_decode_ber;
der_type_encoder_f RailwayLevelCrossingSubCauseCode_encode_der;
xer_type_decoder_f RailwayLevelCrossingSubCauseCode_decode_xer;
xer_type_encoder_f RailwayLevelCrossingSubCauseCode_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RailwayLevelCrossingSubCauseCode_H_ */
#include "asn_internal.h"
