/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#include "RectangularShape.h"

static asn_TYPE_member_t asn_MBR_RectangularShape_1[] = {
	{ ATF_POINTER, 1, offsetof(struct RectangularShape, centerPoint),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CartesianPosition3d,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"centerPoint"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RectangularShape, semiLength),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_StandardLength12b,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"semiLength"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RectangularShape, semiBreadth),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_StandardLength12b,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"semiBreadth"
		},
	{ ATF_POINTER, 2, offsetof(struct RectangularShape, orientation),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Wgs84AngleValue,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"orientation"
		},
	{ ATF_POINTER, 1, offsetof(struct RectangularShape, height),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_StandardLength12b,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"height"
		},
};
static const ber_tlv_tag_t asn_DEF_RectangularShape_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RectangularShape_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* centerPoint */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* semiLength */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* semiBreadth */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* orientation */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* height */
};
static asn_SEQUENCE_specifics_t asn_SPC_RectangularShape_specs_1 = {
	sizeof(struct RectangularShape),
	offsetof(struct RectangularShape, _asn_ctx),
	asn_MAP_RectangularShape_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_RectangularShape = {
	"RectangularShape",
	"RectangularShape",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RectangularShape_tags_1,
	sizeof(asn_DEF_RectangularShape_tags_1)
		/sizeof(asn_DEF_RectangularShape_tags_1[0]), /* 1 */
	asn_DEF_RectangularShape_tags_1,	/* Same as above */
	sizeof(asn_DEF_RectangularShape_tags_1)
		/sizeof(asn_DEF_RectangularShape_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_RectangularShape_1,
	5,	/* Elements count */
	&asn_SPC_RectangularShape_specs_1	/* Additional specs */
};

