/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_ResponseContainer_H_
#define	_ResponseContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ManouevreResponse.h"
#include "DeclineReason.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ListOfSubmanoeuvreDescriptionsContainer;

/* ResponseContainer */
typedef struct ResponseContainer {
	ManouevreResponse_t	 manouevreResponse;
	DeclineReason_t	*declineReason	/* OPTIONAL */;
	struct ListOfSubmanoeuvreDescriptionsContainer	*submaneuvres	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ResponseContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResponseContainer;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ListOfSubmanoeuvreDescriptionsContainer.h"

#endif	/* _ResponseContainer_H_ */
#include "asn_internal.h"
