/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_RoadSegmentReferenceId_H_
#define	_RoadSegmentReferenceId_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Identifier2B.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RoadSegmentReferenceId */
typedef struct RoadSegmentReferenceId {
	Identifier2B_t	*region	/* OPTIONAL */;
	Identifier2B_t	 id;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RoadSegmentReferenceId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RoadSegmentReferenceId;

#ifdef __cplusplus
}
#endif

#endif	/* _RoadSegmentReferenceId_H_ */
#include "asn_internal.h"
