/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_SafeDistanceIndicator_H_
#define	_SafeDistanceIndicator_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BOOLEAN.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SafeDistanceIndicator */
typedef BOOLEAN_t	 SafeDistanceIndicator_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SafeDistanceIndicator;
asn_struct_free_f SafeDistanceIndicator_free;
asn_struct_print_f SafeDistanceIndicator_print;
asn_constr_check_f SafeDistanceIndicator_constraint;
ber_type_decoder_f SafeDistanceIndicator_decode_ber;
der_type_encoder_f SafeDistanceIndicator_encode_der;
xer_type_decoder_f SafeDistanceIndicator_decode_xer;
xer_type_encoder_f SafeDistanceIndicator_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SafeDistanceIndicator_H_ */
#include "asn_internal.h"
