/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_SequenceOfIdentifier1B_H_
#define	_SequenceOfIdentifier1B_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Identifier1B.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceOfIdentifier1B */
typedef struct SequenceOfIdentifier1B {
	A_SEQUENCE_OF(Identifier1B_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceOfIdentifier1B_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceOfIdentifier1B;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceOfIdentifier1B_H_ */
#include "asn_internal.h"
