/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_Submanoeuvre_H_
#define	_Submanoeuvre_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Identifier1B.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Trajectory;
struct AdvisedTrrContainer;

/* Submanoeuvre */
typedef struct Submanoeuvre {
	Identifier1B_t	 submanoeuvreId;
	struct Trajectory	*advisedTrajectory	/* OPTIONAL */;
	struct AdvisedTrrContainer	*advisedTargetRoadResource	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Submanoeuvre_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Submanoeuvre;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Trajectory.h"
#include "AdvisedTrrContainer.h"

#endif	/* _Submanoeuvre_H_ */
#include "asn_internal.h"
