/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_TemporalCharacteristics_H_
#define	_TemporalCharacteristics_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TemporalCharacteristics */
typedef struct TemporalCharacteristics {
	long	 tRROccupancyStartTime;
	long	 tRROccupancyEndTime;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TemporalCharacteristics_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TemporalCharacteristics;

#ifdef __cplusplus
}
#endif

#endif	/* _TemporalCharacteristics_H_ */
#include "asn_internal.h"
