/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_TrrDescription_H_
#define	_TrrDescription_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TrrType.h"
#include "LaneCount.h"
#include "TRRWidth.h"
#include "TRRLength.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PathPoint;
struct Wgs84Angle;

/* TrrDescription */
typedef struct TrrDescription {
	TrrType_t	 trrType;
	LaneCount_t	 laneCount;
	LaneCount_t	*startingLaneNumber	/* OPTIONAL */;
	LaneCount_t	*endingLaneNumber	/* OPTIONAL */;
	struct TrrDescription__waypoints {
		A_SEQUENCE_OF(struct PathPoint) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *waypoints;
	struct TrrDescription__heading {
		A_SEQUENCE_OF(struct Wgs84Angle) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *heading;
	TRRWidth_t	 trrWidth;
	TRRLength_t	 trrLength;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TrrDescription_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TrrDescription;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "WayPoint.h"
#include "Wgs84Angle.h"

#endif	/* _TrrDescription_H_ */
#include "asn_internal.h"
