/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_TRRWidth_H_
#define	_TRRWidth_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TRRWidth */
typedef long	 TRRWidth_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TRRWidth;
asn_struct_free_f TRRWidth_free;
asn_struct_print_f TRRWidth_print;
asn_constr_check_f TRRWidth_constraint;
ber_type_decoder_f TRRWidth_decode_ber;
der_type_encoder_f TRRWidth_encode_der;
xer_type_decoder_f TRRWidth_decode_xer;
xer_type_encoder_f TRRWidth_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _TRRWidth_H_ */
#include "asn_internal.h"
