/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_TurningDirection_H_
#define	_TurningDirection_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TurningDirection {
	TurningDirection_left	= 0,
	TurningDirection_right	= 1
} e_TurningDirection;

/* TurningDirection */
typedef long	 TurningDirection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TurningDirection;
asn_struct_free_f TurningDirection_free;
asn_struct_print_f TurningDirection_print;
asn_constr_check_f TurningDirection_constraint;
ber_type_decoder_f TurningDirection_decode_ber;
der_type_encoder_f TurningDirection_encode_der;
xer_type_decoder_f TurningDirection_decode_xer;
xer_type_encoder_f TurningDirection_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _TurningDirection_H_ */
#include "asn_internal.h"
