/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_VehicleManoeuvreContainer_H_
#define	_VehicleManoeuvreContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "VehicleCurrentStateContainer.h"
#include "ListOfSubmanoeuvreDescriptionsContainer.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ManoeuvreAdviceContainer;

/* VehicleManoeuvreContainer */
typedef struct VehicleManoeuvreContainer {
	VehicleCurrentStateContainer_t	 vehicleCurrentStateContainer;
	ListOfSubmanoeuvreDescriptionsContainer_t	 submaneuvres;
	struct ManoeuvreAdviceContainer	*manoeuvreAdvice	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleManoeuvreContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleManoeuvreContainer;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ManoeuvreAdviceContainer.h"

#endif	/* _VehicleManoeuvreContainer_H_ */
#include "asn_internal.h"
