/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#include "VehicleCurrentStateContainer.h"

static asn_TYPE_member_t asn_MBR_VehicleCurrentStateContainer_1[] = {
	{ ATF_POINTER, 1, offsetof(struct VehicleCurrentStateContainer, manoeuvreOverallStrategy),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ManoeuvreOverallStrategy,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"manoeuvreOverallStrategy"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct VehicleCurrentStateContainer, vehicleSpeed),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Speed,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vehicleSpeed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct VehicleCurrentStateContainer, vehicleHeading),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Wgs84Angle,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vehicleHeading"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct VehicleCurrentStateContainer, vehicleSize),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleSize,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vehicleSize"
		},
};
static const ber_tlv_tag_t asn_DEF_VehicleCurrentStateContainer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_VehicleCurrentStateContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* manoeuvreOverallStrategy */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* vehicleSpeed */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* vehicleHeading */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* vehicleSize */
};
static asn_SEQUENCE_specifics_t asn_SPC_VehicleCurrentStateContainer_specs_1 = {
	sizeof(struct VehicleCurrentStateContainer),
	offsetof(struct VehicleCurrentStateContainer, _asn_ctx),
	asn_MAP_VehicleCurrentStateContainer_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_VehicleCurrentStateContainer = {
	"VehicleCurrentStateContainer",
	"VehicleCurrentStateContainer",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_VehicleCurrentStateContainer_tags_1,
	sizeof(asn_DEF_VehicleCurrentStateContainer_tags_1)
		/sizeof(asn_DEF_VehicleCurrentStateContainer_tags_1[0]), /* 1 */
	asn_DEF_VehicleCurrentStateContainer_tags_1,	/* Same as above */
	sizeof(asn_DEF_VehicleCurrentStateContainer_tags_1)
		/sizeof(asn_DEF_VehicleCurrentStateContainer_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_VehicleCurrentStateContainer_1,
	4,	/* Elements count */
	&asn_SPC_VehicleCurrentStateContainer_specs_1	/* Additional specs */
};

