/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#include "Velocity3dWithConfidence.h"

static asn_TYPE_member_t asn_MBR_Velocity3dWithConfidence_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Velocity3dWithConfidence, choice.polarVelocity),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VelocityPolarWithZ,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"polarVelocity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Velocity3dWithConfidence, choice.cartesianVelocity),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VelocityCartesian,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cartesianVelocity"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Velocity3dWithConfidence_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* polarVelocity */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* cartesianVelocity */
};
static asn_CHOICE_specifics_t asn_SPC_Velocity3dWithConfidence_specs_1 = {
	sizeof(struct Velocity3dWithConfidence),
	offsetof(struct Velocity3dWithConfidence, _asn_ctx),
	offsetof(struct Velocity3dWithConfidence, present),
	sizeof(((struct Velocity3dWithConfidence *)0)->present),
	asn_MAP_Velocity3dWithConfidence_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Velocity3dWithConfidence = {
	"Velocity3dWithConfidence",
	"Velocity3dWithConfidence",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_Velocity3dWithConfidence_1,
	2,	/* Elements count */
	&asn_SPC_Velocity3dWithConfidence_specs_1	/* Additional specs */
};

