/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_VelocityComponent_H_
#define	_VelocityComponent_H_


#include "asn_application.h"

/* Including external dependencies */
#include "VelocityComponentValue.h"
#include "SpeedConfidence.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VelocityComponent */
typedef struct VelocityComponent {
	VelocityComponentValue_t	 value;
	SpeedConfidence_t	 confidence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VelocityComponent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VelocityComponent;

#ifdef __cplusplus
}
#endif

#endif	/* _VelocityComponent_H_ */
#include "asn_internal.h"
