/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#include "VruProfileAndSubprofile.h"

static asn_TYPE_member_t asn_MBR_VruProfileAndSubprofile_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct VruProfileAndSubprofile, choice.pedestrian),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VruSubProfilePedestrian,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"pedestrian"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct VruProfileAndSubprofile, choice.bicyclistAndLightVruVehicle),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VruSubProfileBicyclist,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bicyclistAndLightVruVehicle"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct VruProfileAndSubprofile, choice.motorcyclist),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VruSubProfileMotorcyclist,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"motorcyclist"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct VruProfileAndSubprofile, choice.animal),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VruSubProfileAnimal,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"animal"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_VruProfileAndSubprofile_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pedestrian */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* bicyclistAndLightVruVehicle */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* motorcyclist */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* animal */
};
static asn_CHOICE_specifics_t asn_SPC_VruProfileAndSubprofile_specs_1 = {
	sizeof(struct VruProfileAndSubprofile),
	offsetof(struct VruProfileAndSubprofile, _asn_ctx),
	offsetof(struct VruProfileAndSubprofile, present),
	sizeof(((struct VruProfileAndSubprofile *)0)->present),
	asn_MAP_VruProfileAndSubprofile_tag2el_1,
	4,	/* Count of tags in the map */
	0,
	4	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_VruProfileAndSubprofile = {
	"VruProfileAndSubprofile",
	"VruProfileAndSubprofile",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_VruProfileAndSubprofile_1,
	4,	/* Elements count */
	&asn_SPC_VruProfileAndSubprofile_specs_1	/* Additional specs */
};

