/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_VruSubProfileMotorcyclist_H_
#define	_VruSubProfileMotorcyclist_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VruSubProfileMotorcyclist {
	VruSubProfileMotorcyclist_unavailable	= 0,
	VruSubProfileMotorcyclist_moped	= 1,
	VruSubProfileMotorcyclist_motorcycle	= 2,
	VruSubProfileMotorcyclist_motorcycle_and_sidecar_right	= 3,
	VruSubProfileMotorcyclist_motorcycle_and_sidecar_left	= 4,
	VruSubProfileMotorcyclist_max	= 15
} e_VruSubProfileMotorcyclist;

/* VruSubProfileMotorcyclist */
typedef long	 VruSubProfileMotorcyclist_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VruSubProfileMotorcyclist;
asn_struct_free_f VruSubProfileMotorcyclist_free;
asn_struct_print_f VruSubProfileMotorcyclist_print;
asn_constr_check_f VruSubProfileMotorcyclist_constraint;
ber_type_decoder_f VruSubProfileMotorcyclist_decode_ber;
der_type_encoder_f VruSubProfileMotorcyclist_encode_der;
xer_type_decoder_f VruSubProfileMotorcyclist_decode_xer;
xer_type_encoder_f VruSubProfileMotorcyclist_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _VruSubProfileMotorcyclist_H_ */
#include "asn_internal.h"
