/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_VruSubProfileAnimal_H_
#define	_VruSubProfileAnimal_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VruSubProfileAnimal {
	VruSubProfileAnimal_unavailable	= 0,
	VruSubProfileAnimal_wild_animal	= 1,
	VruSubProfileAnimal_farm_animal	= 2,
	VruSubProfileAnimal_service_animal	= 3,
	VruSubProfileAnimal_max	= 15
} e_VruSubProfileAnimal;

/* VruSubProfileAnimal */
typedef long	 VruSubProfileAnimal_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VruSubProfileAnimal;
asn_struct_free_f VruSubProfileAnimal_free;
asn_struct_print_f VruSubProfileAnimal_print;
asn_constr_check_f VruSubProfileAnimal_constraint;
ber_type_decoder_f VruSubProfileAnimal_decode_ber;
der_type_encoder_f VruSubProfileAnimal_encode_der;
xer_type_decoder_f VruSubProfileAnimal_decode_xer;
xer_type_encoder_f VruSubProfileAnimal_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _VruSubProfileAnimal_H_ */
#include "asn_internal.h"
