/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_WayPointType_H_
#define	_WayPointType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum WayPointType {
	WayPointType_startingWayPoint	= 0,
	WayPointType_intermediateWayPoint	= 1,
	WayPointType_endingWayPoint	= 2
} e_WayPointType;

/* WayPointType */
typedef long	 WayPointType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WayPointType;
asn_struct_free_f WayPointType_free;
asn_struct_print_f WayPointType_print;
asn_constr_check_f WayPointType_constraint;
ber_type_decoder_f WayPointType_decode_ber;
der_type_encoder_f WayPointType_encode_der;
xer_type_decoder_f WayPointType_decode_xer;
xer_type_encoder_f WayPointType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _WayPointType_H_ */
#include "asn_internal.h"
